- build.sh
- plugins/cloudtrail/go.mod
- plugins/cloudtrail/go.sum
- plugins/dummy/go.mod
- plugins/dummy/go.sum
- plugins/json/go.mod
- plugins/json/go.sum
This ensures the official version of plugin-sdk-go will be used.
Also add a minimal build.sh script that just invokes make.
> Update go.mod/go.sum to use falcosecurity/plugin-sdk-go

- plugins/dummy/dummy.go
- plugins/dummy_c/dummy.cpp
Event numbers are assigned by the plugin framework, not plugins, so
don't set them when returning values in plugin_next().
> /kind bug
/kind cleanup
> /kind design
> /area build
Fixes #
```release-note
Don't fill in event numbers in plugin_next(), they're allocated by the plugin …
```
> Don't return event numbers in plugin_next()

- plugins/cloudtrail/README.md
- plugins/cloudtrail/cloudtrail.go
More useful than extracting using json/jevt plugins.
> /kind bug
> /kind design
/kind feature
> /area build
Fixes #
```release-note
Add ct.error field to cloudtrail plugin.
```
> Add a ct.error field to extract errors

- plugins/cloudtrail/cloudtrail.go
- plugins/dummy/dummy.go
- plugins/dummy_c/dummy.cpp
- plugins/json/json.go
Instead of starting with a bold 1.0.0 for the initial plugins api
version, we're going to start with a more reasonable 0.1.0. While
we're at it, let's use an initial version of 0.1.0 for all plugin
versions.
After this, the plugin versions will progress independently from each
other and from the api version.
> /kind bug
/kind cleanup
> /kind design
/area extractor-plugins
> /area build
Fixes # …
> Use an initial version of 0.1.0 for plugins/plugin api

- plugins/cloudtrail/cloudtrail.go
/kind bug
/area extractor-plugins
This PR fixes the `cloudtrail` plugin, which currently fails to read the `init` configuration.
```release-note
NONE
```
> fix(cloudtrail): properly read init config

- plugins/dummy_c/dummy.cpp
- sdk/cpp/falcosecurity_plugin.h
/kind bug
/kind feature
This PR alignes the cpp SDK and the `dummy_c` plugin to the changes of https://github.com/falcosecurity/libs/pull/168, thus supporting catching errors during plugin initialization.
```release-note
fix(sdk/cpp): catch errors during plugin initialization
```
> fix(sdk/cpp): catch errors during plugin initialization

- Makefile
- build/utils/.gitignore
- build/utils/Makefile
- build/utils/go.mod
- build/utils/go.sum
- build/utils/version.go
- plugins/cloudtrail/Makefile
- plugins/dummy/Makefile
- plugins/json/Makefile
- release.md
Co-authored-by: Leonardo Grasso <me@leonardograsso.com>
/kind design
/kind feature
/area build
This updates the Makefile to support building plugins for release purposes, and adds a tool to automatically compute a SemVer-compatible version number that will be used by the CI to build/publish both pre-release and release packages.
Fixes #19 
Fixes #35
```release-note
build: adding release utils for plugin distribution
```
> build: adding release utils for plugin distribution

- plugins/cloudtrail/cloudtrail.go
- plugins/cloudtrail/go.mod
- plugins/cloudtrail/go.sum
- plugins/dummy/dummy.go
- plugins/dummy/go.mod
- plugins/dummy/go.sum
/kind feature
This adds support for the init configuration schema feature of https://github.com/falcosecurity/plugin-sdk-go/pull/35 to the `cloudtrail` and `dummy` plugins. This allows for an easier and cleaner parsing of the init configuration, and provides a well-documented schema for it.
```release-note
update(plugins): support init config schema in cloudtrail and dummy
```
> update(plugins): support init config schema in cloudtrail and dummy

- .github/PULL_REQUEST_TEMPLATE.md
/kind cleanup
This removes the release note block from the PR template, as it's not required anymore due to the changes of https://github.com/falcosecurity/test-infra/pull/604
> update(.github): remove release note from PR template

- .github/PULL_REQUEST_TEMPLATE.md
/kind cleanup
Given the recent changes in this repository, this removes the PR template as follows:
- Remove `source-plugins` and `extractor-plugins` area labels, unifying them in a single `plugins` area
- Add an area label for `registry`
> update(.github): add registry kind in PR template and unify plugins area

- README.md
Updating README.md (automatically generated with build/registry). Made using the [build-plugins-update-readme-postsubmit](https://github.com/falcosecurity/test-infra/blob/master/config/jobs/build-plugins/build-plugins.yaml) ProwJob. Do not edit this PR.
> docs(README.md): update plugin registry table

- plugins/cloudtrail/cloudtrail.go
NextBatch is presented a long array of sdk.EventWriters and associates
events with them until the first error (which could include
eof/timeout).
If the last event results in an error, the loop would increment n,
then check the error, then return. n would be one bigger than
expected.
Fix this by checking for error + breaking inside the loop instead of
checking for error in the loop condition.
/kind bug
> /kind design
/area plugins
> /area build
**What this PR …
> Fix off-by-one error in NextBatch

- plugins/json/json.go
/kind bug
/area plugins
This fixes the issue of #56. The `json` plugin relied on the `fastjson.MarshalTo` function, which unwillingly added the `"` quotes around strings and caused the Falco rules to not match string values properly.
Fixes #56
> fix(plugins/json): fix quoting and escaping in string-based json.value

- plugins/cloudtrail/extract.go
@ldegio pointed out that `ct.error` will return "field not present" if
the object does not have an `errorCode` property.
From the perspective of rules files, this ends up being the string
"&lt;NA&gt;", as that's how a NULL filtercheck value is represented as a
string.
This fixes the help text to reflect that.
> /kind bug
> /kind design
/area plugins
> /area build
Fixes #
**Special notes …
> Update desc text for ct.error (not found value)

- plugins/cloudtrail/cloudtrail.go
/kind cleanup
/area plugins
This completes https://github.com/falcosecurity/plugins/pull/60, in which the `cloudtrail` plugin version was not bumped.
> update(plugins/cloudtrail): bump plugin version to 0.2.3

- README.md
- build/registry/check.go
/kind design
/area registry
This removes the uniqueness constraint that we used to put on the source name of plugins. I makes sense for plugins with different IDs to share the same source name **if they share the same event data format**. This can allow different plugin implementations of the same event source to co-exist in the ecosystem (and in the registry).
> fix(registry): remove uniqueness constraint on source name

- plugins/cloudtrail/source.go
Signed-off-by: Andrea Terzolo <andrea.terzolo@polito.it>
/kind bug
/area plugins
Cloudtrail empty files cause problems in reading events. The format is the following:
```json
{
"Records": []
}
```
Reading an empty file, the variable `len(oCtx.evtJSONStrings)` is always `0` so at line [403](https://github.com/falcosecurity/plugins/blob/4695796c8eba65a49a2a94581346aae2298aec25/plugins/cloudtrail/source.go#L403) we increment the `oCtx.evtJSONListPos`, but when we try to extract the next event from this file the `oCtx.evtJSONListPos` will be greater than `len(oCtx.evtJSONStrings)`. [This if statement](https://github.com/falcosecurity/plugins/blob/4695796c8eba65a49a2a945 …
> fix(plugin/cloudtrail): manage cloudtrail empty file.

- plugins/cloudtrail/cloudtrail.go
- plugins/cloudtrail/extract.go
Many of the events in a Cloudtrail scap here have floating point
bytesTransferred{In,Out} values, e.g.
"additionalEventData": {
"SignatureVersion": "SigV4",
"CipherSuite": "ECDHE-RSA-AES128-GCM-SHA256",
"bytesTransferredIn": 0.0,
"AuthenticationMethod": "AuthHeader",
"x-amz-id-2": "Y/9E1+wcb4G90kzKPJ9K66wa+AIGssOLXHWQ7isdbcNc2OzUGBTYH4I7zjeZ3AR2zjn0oTuLZI4=",
"bytesTransferredOut": 33.0
}
This is arguably a bug with Cloudtrail, but here we are. Try parsing
them as Uint64 first, then fall back to Float64.
Signed-off-by: Gerald Combs <gerald@wireshark.org>
/kind bug
> /kind design
> …
> Cloudtrail: Handle floating point values.

- Makefile
/kind cleanup
/area build
This PR allows building and publishing plugin packages even if the README.md file is missing. So far, commands such as `make package/<plugin>` to fail if a readme is not found, which also blocks the publishing system of the CI. I still think putting readmes is valuable, but I don't see this as a publication requirement, especially for dev builds.
> chore(build): allow publishing packages without README.md

- Makefile
- README.md
- build/registry/check.go
- build/registry/registry.go
- build/registry/table.go
- build/registry/types.go
- registry.yaml
/kind cleanup
/kind design
/area registry
Following up the progress of tracked in https://github.com/falcosecurity/falco/issues/1948, this PR refactors the plugin registry, the registry tool, and the readme, to reflect the recent changes of the plugin API that removed the notion of "plugin type".
> refactor(registry): re-design plugin registry on top of new capabilities model

- plugins/cloudtrail/extract.go
> /kind bug
/kind cleanup
> /kind design
/area plugins
> /area build
This ensures that the cloudtrail plugin always fills in the ct.info field. The the user, source IP, and event type are filled in by default, along with extra information for some event types. Reads are denoted with left arrows, writes are denoted with right arrows, and errors are denoted with exclamation marks. Examples:
user1 via 54.5.4.3 ← DescribeDBInstances
AWSServiceRoleForECS via ecs.amazonaws.com → …
> update(cloudtrail): Always fill in ct.info and add ct.managementevent

- plugins/k8saudit/README.md
- plugins/k8saudit/pkg/k8saudit/source.go
/kind bug
/area plugins
This fixes a bug on the k8saudit plugin that prevented its webserver to be started on arbitrary hosts. Previously, the host of open parameters such as `http://...` or `https://...` was resolved by using a regex due to code leftover from the initial development phase. This PR fixes this by using `url.Parse` to retrieve the same info.
> fix(plugins/k8saudit): fix webserver host resolution

- plugins/cloudtrail/pkg/cloudtrail/cloudtrail.go
- plugins/cloudtrail/rules/aws_cloudtrail_rules.yaml
- plugins/dummy/pkg/dummy/dummy.go
- plugins/json/pkg/json/json.go
- plugins/k8saudit/rules/k8s_audit_rules.yaml
- plugins/okta/pkg/okta/okta.go
/kind cleanup
/area plugins
This bumps the version of the following plugins: cloudtrail, json, okta, and dummy. These new versions are release candidates to be bundled in Falco 0.32. In all of them, the version increased the minor due to the breaking changes introduced in the plugin API and propagated to the newly-released Plugin SDK Go v0.3.0.
There are no breaking changes in the plugin's code or their UX that motivates a major version bump.
> update(plugins): bump version of cloudtrail, json, okta, and dummy

- plugins/k8saudit/pkg/k8saudit/config.go
- plugins/k8saudit/pkg/k8saudit/source.go
/kind bug
/area plugins
This fixes an issue with the k8saudit plugin. The K8S API server occasionally sends large JSON events, which can cause Falco to exit with error due to the allocated plugin event batch being too short to write an event. We make this non-blocking by checking the event size prior writing it into the batch, and dropping it with a logged message in case it is too large.
> fix(plugins/k8saudit): drop events larger than max evt size 

- plugins/cloudtrail/README.md
- plugins/cloudtrail/pkg/cloudtrail/source.go
/kind bug
> /kind design
/area plugins
> /area build
Recently a behavior in the cloudtrail plugin ( https://github.com/falcosecurity/plugins/pull/94 ) has been documented as a limitation. Specifically, we couldn't parse `json` files on S3 but only `json.gz`. This is actually a bug that can be easily fixed by setting `isCompressed` correctly.
No version bump for plugins is required at this time.
Fixes #
**Special notes for your …
> fix(cloudtrail): support plain text json logs on S3

- plugins/k8saudit/pkg/k8saudit/k8saudit.go
- plugins/k8saudit/pkg/k8saudit/source.go
/kind bug
/area plugins
When the event source gets closed by the plugin due to lack of new events (this only happens when reading json events from file right now), the error returned by `NextBatch` was non-deterministically either `nil` or `sdk.ErrEOF`. In the current implementation of the plugin framework, returning empty event batches with `nil` error is interpreted as an unsafe corner case which causes a libscap-level failure. As a consequence, some Falco tests became flaky due to the program exit code being 1 or 0 with non-determinism. 
The root cause of this issue is the k8saudit plugin, which …
> fix(plugins/k8saudit): return non-nil error from NextBatch with closed channel

- plugins/k8saudit/go.mod
- plugins/k8saudit/go.sum
- plugins/k8saudit/pkg/k8saudit/source.go
/kind design
/kind feature
/area plugins
This PR refactors the `k8saudit` plugin to leverage the new prebuilt-implementation of `source.Instance` provided by the SDK Go since merging https://github.com/falcosecurity/plugin-sdk-go/pull/50. This is a first experiment of this approach, which could be used by other plugins once we are confident of its benefits.
Visible benefits so far:
- Smaller and more readable code
- The termination condition of the event source is more clear and regulated by only one channel
- Performance should be better since now we reuse a …
> refactor(plugins/k8saudit): re-implement k8saudit event source using the SDK Go prebuilts

- plugins/dummy/README.md
- plugins/dummy/pkg/dummy/dummy.go
/kind design
/area plugins
The dummy plugin serves as a piece of documentation for newcomers contributors to learn how to use the SDK Go. In fact, it is also used in the Falco website in the SDK Go walkthrough section. However, the plugin was implemented during the early days of the plugin system and the SDK Go, so it does not use some of the newest best practices. This PR refactors the dummy plugin accordingly.
These changes require a version bump of the plugin. The proposed new tag is v0.6.0. If merged, the code-snippet documentation on the Falco website …
> refactor(plugins/dummy): update dummy plugins to new SDK Go best practices

- plugins/github/pkg/github/github.go
- plugins/github/pkg/github/server.go
/kind bug
/area plugins
The patch diff parsing function was fragile and rejected cases like `"@@ -0,0 +1 @@\n+sample line\n"`. This has been fixed by using regular expressions.
> fix(plugins/github): correctly parse patch diffs 

- plugins/k8saudit/README.md
- plugins/k8saudit/pkg/k8saudit/extract.go
- plugins/k8saudit/pkg/k8saudit/fields.go
/kind feature
/area plugins
The audit event log has sourceIPs field but it ignored in k8saudit plugin.
This sourceIPs field enables to audit who and where calls Kubernetes api, and helps incident investigation.
Fixes #
> add ka.sourceips in k8saudit plugin

- plugins/k8saudit/rules/k8s_audit_rules.yaml
Signed-off-by: Hi120ki <12624257+hi120ki@users.noreply.github.com>
> /kind bug
> /kind design
/kind feature
/area plugins
> /area build
In k8s audit detection rule, containerd socket is missing in Create Sensitive Mount Pod rule's sensitive_vol_mount list.
Fixes #
> add containerd.sock to sensitive_vol_mount

- Makefile
/kind cleanup
/kind design
/area build
This is required because some tools (ie. falcoctl or other custom scripts) may use the `.tar.gz` to install a plugin into the default location (ie, `/usr/share/falco/plugins`. In such cases, the README.md file should be not installed.
Removing it from the packages will avoid the need of implementing custom logic for that across different tools.
Fixes #
> build: do not include README.md in packages

- build/oci/pkg/output/output.go
Co-authored-by: Lorenzo Susini <susinilorenzo1@gmail.com>
/kind bug
> /kind design
/area registry
> /area build
Fix the read from file in the `output` package under the oci-tool.
Fixes #
> fix(oci-tool/output): porperly populate the map entries when reading from file

- plugins/k8saudit/pkg/k8saudit/source.go
/kind bug
/area plugins
Currently, the plugin tries to open any string which is provided to open_params. This succeeds for filepaths but fails if it is point to a directory. 
This PR adds the logic to check if the input string refers to a single file or to a directory.
Fixes #182 
It would be cool if this can be tagged with hacktoberfest
> fix(plugins/k8saudit): Recursively parse the files in a directory

- plugins/k8saudit/pkg/k8saudit/source.go
/kind bug
/area plugins
As in #183, the k8saudit plugin's webserver panics when an event capture is forcefully closed. This happens due to the `serverEvtChan` channel being closed before all events have finished being pushed. However, this issue comes from the limited control that we have on the webserver's behavior. Essentially, when we shutdown the server we wait for all open connections to be closed, but we have no control on the ones that are waiting to push data into the channel. This can be fixed in different ways, but the less troublesome one is to isolate the data sending function and recover from …
> fix(plugins/k8saudit): prevent panics while shutting down webserver

- build/registry/cmd/registry/registry.go
- build/registry/pkg/registry/load.go
- build/registry/pkg/registry/oci/oci.go
…s commands
> /kind bug
/kind cleanup
> /kind design
/area registry
> /area build
Make `LoadRegistryFromFile()` function reusable and remove duplicated code from `oci command`.
Fixes #
> refactor(ci/build): make LoadRegistryFromFile function reusable across commands

- build/registry/go.mod
- build/registry/go.sum
- build/registry/pkg/common/consts.go
- build/registry/pkg/common/extract.go
- build/registry/pkg/oci/configLayer.go
- build/registry/pkg/oci/dependencies.go
- build/registry/pkg/oci/oci.go
- build/registry/pkg/oci/requirements.go
> /kind bug
> /kind design
/kind feature
/area registry
/area build
The CI before pushing the artifacts to the remote registry it correctly configures the `config` layer by adding dependencies and requirements. 
The `rulesfiles` could depend on `plugins` meaning that they need a specific version of a plugin in order to be consumed. At the same time they require that the  Falco `engine version` needs to satisfy the minimum version specified …
> feat(build/registry): add config layer to artifacts when pushing to registry

- plugins/cloudtrail/go.mod
- plugins/cloudtrail/pkg/cloudtrail/source.go
Try to construct error messages from smithy.APIError and smithy.OperationError, which gives us access to human-readable strings.
> /kind bug
/kind cleanup
> /kind design
/area plugins
> /area build
This helps to ensure that the cloudtrail plugin produces human-readable error messages.
Examples:
Expired token:
Old:
> cloudtrail plugin error: failed to list objects: operation error S3: ListObjectsV2, https response error StatusCode: 400, RequestID: Q2TAHZQ6FCC0FT7S, HostID: …
> update(plugins/cloudtrail): More friendly error messages

- build/registry/pkg/oci/requirements.go
/kind bug
> /kind design
/area registry
/area build
Since the `engine_version` does not follow the `semver` convention, we need to set is as it is in the config layer of the `rulesfiles` artifacts.
Fixes #
> update(build/registry): do not set the engine_version in semver format in the config file

- plugins/k8saudit-eks/README.md
/area plugins
Adds small section to readme of k8saudit-eks plugin documenting the required AWS IAM policy permissions. There are not documented anywhere else at the moment.
Fixes #211
Policy document does not contain the absolute minimum of permissions. Checking the code, at the moment only `logs:FilterLogEvents` is used. So we could remove the other three actions with wildcards from the policy. But then users might have to adjust their policies in the future should the plugin start to use other actions as well.
Including @Issif as major developer of plugin.
> docs(plugins/k8saudit-eks): document required aws iam permissions

- plugins/k8saudit/rules/k8s_audit_rules.yaml
Signed-off-by: Tim Schwenke <tim@trallnag.com>
/kind bug
/area plugins
There is a missing comma. This leads to two items in the list getting merged into one item.
Fixes #217
> fix(plugin/k8saudit): Add missing comma to list entry in rule

- plugins/k8saudit/rules/k8s_audit_rules.yaml
Signed-off-by: Tim Schwenke <tim@trallnag.com>
/kind feature
/area plugins
Adds two users `eks:vpc-resource-controller` and `eks:cloud-controller-manager` to `eks_allowed_k8s_users` list in `k8s_audit_rules.yaml`.
Needed because these users are standard users in EKS.
For more information see related issue.
**Which issue(s) this PR fixes**: 
Fixes #216 
The user `eks:vpc-resource-controller` is part of the official EKS add-on [VPC CNI](https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html). For example mentioned here in this documentation: https://docs.aws.amazon.com/eks/latest/userguide/security-groups-for-pods.html
The cluster role `eks:cloud-controller-manager` belongs to the AWS implementation / extension of the cloud controller …
> Add additional known users to eks_allowed_k8s_users

- build/registry/pkg/distribution/index.go
/kind bug
/area registry
Including the plugin name in the index keywords improves the UX `falcoctl artifact search`, since we also do it for rules already. For example, `falcoctl artifact search cloud` will currently only match the `cloudtrail-rules` artifact, whereas I would expect `cloudtrail` to be a match too.
> fix(build/registry): add plugin name as a keyword in index

- plugins/k8saudit/rules/k8s_audit_rules.yaml
/kind cleanup
/area plugins
- update k8s registry domain
part of https://github.com/kubernetes/k8s.io/issues/4780
/assign @leogr 
Fixes #
> update k8s registry domain

- build/registry/pkg/oci/const.go
- build/registry/pkg/oci/oci.go
Use "arm64" as architecture for plugins build for the arm platform instead of "aarch64".
/kind bug
> /kind design
/area registry
> /area build
Use "arm64" as architecture for plugins build for the arm platform instead of "aarch64".
Fixes #
> fix(oci/CI): set arm architecture as "arm64" in manifests files

- plugins/cloudtrail/pkg/cloudtrail/extract.go
If ct.user and ct.srcip are the same, just add ct.user to the event info string so that we return
cloudtrail.amazonaws.com ← GetBucketAcl
instead of
cloudtrail.amazonaws.com via cloudtrail.amazonaws.com ← GetBucketAcl
> /kind bug
/kind cleanup
> /kind design
/area plugins
> /area build
It avoids adding duplicate information to Cloudtrail's event information string.
Fixes #
> update(plugins/cloudtrail): Avoid duplicate event info

- plugins/k8saudit/rules/k8s_audit_rules.yaml
/kind feature
/area plugins
Extends macros that match call to Kubernetes control plane health check endpoints to include query parameters. This is supported by Kubernetes officially, see [link](https://kubernetes.io/docs/reference/using-api/health-checks/).
Fixes #241
> feat(plugins/k8saudit): include query params in health check url macros

- build/registry/pkg/distribution/index.go
/kind bug
> /kind design
/area registry
> /area build
The artifact name is added to the list of keywords when generating the [index.yaml](https://falcosecurity.github.io/falcoctl/index.yaml) file. It could happen that the list of keywords in `registry.yaml` already contains the artifact name. This fix checks if the artifact name is contained in the keywords, if not adds it.
Fixes #
> fix(registry/index): do not add artifact name to keywords if already present

- .github/workflows/release.yml
/kind cleanup
/area build
The concurrency of release jobs should be grouped by plugin (represented by their tag's git ref, at release time), instead of being grouped all together.
> update(ci/release.yaml): setup per-plugin release concurrency

- plugins/cloudtrail/pkg/cloudtrail/config.go
Change the default value of S3DownloadConcurrency from 1 to 32. This improves performance noticeably here.
> /kind bug
/kind cleanup
> /kind design
/area plugins
> /area build
This sets the default download concurrency to 32. This improves performance significantly in my tests here.
Fixes #
> update(plugins/cloudtrail): Increase our default S3 concurrency

- .github/workflows/upload-oci-artifacts.yaml
- build/registry/cmd/registry/registry.go
- build/registry/go.mod
- build/registry/internal/options/options.go
- build/registry/pkg/oci/oci.go
- build/registry/pkg/oci/oci_suite_test.go
- build/registry/pkg/oci/registry.go
- build/registry/pkg/oci/registry_test.go
- build/registry/pkg/registry/types.go
/kind feature
/area registry
/area build
To provide signatures for the plugin OCI artifacts, as OCI artifacts, with cosign.
Fixes #244 
This is part of the work for providing signatures for Falco artifacts, alongside:
- Rules signing: https://github.com/falcosecurity/rules/issues/65 and https://github.com/falcosecurity/rules/pull/66
- Artifact signature verification with [falcoctl](https://github.com/falcosecurity/falcoctl): https://github.com/falcosecurity/falcoctl/issues/174 and https://github.com/falcosecurity/falcoctl/pull/305
> Introduce OCI artifacts signatures

- .github/workflows/reusable_build_rules_tool.yaml
/kind bug
/area build
Attempts fixing the CI issues that we have on mainline when validating plugins. These seem to be related to https://github.com/moby/buildkit/pull/4043. We pull a version of the docker client with the issue from https://github.com/falcosecurity/rules/tree/main/build/checker. Once a new version of the client gets released, we should update the rules checker tool, but for now we can just build with a less recent go version.
> fix(ci): solve issues with docker

- plugins/k8saudit-eks/OWNERS
> /kind bug
> /kind design
/area plugins
> /area build
I'm proposing myself as approver of the `k8saudit-eks` plugin, as I developed it, it seems logical to be able to review proposals from the community.
Fixes #
> vote: add Issif as approvers for k8saudit-eks plugin

- .github/compare-rule-files.sh
- .github/get-latest-plugin-version.sh
- .github/setup-plugin-config-rules.sh
- .github/workflows/ci.yaml
- .github/workflows/master.yaml
- .github/workflows/release.yml
- .github/workflows/reusable_get_changed_plugins.yaml
- .github/workflows/reusable_validate_plugins.yaml
- .github/workflows/rules.yaml
- plugins/cloudtrail/rules/aws_cloudtrail_rules.yaml
- plugins/gcpaudit/pkg/gcpaudit/gcpaudit.go
- plugins/gcpaudit/rules/gcp_auditlog_rules.yaml
/kind bug
/kind cleanup
/area build
Our release workflow might fail when validating the locally-built plugins due to potentially-required plugins being missing. This happens because at release time we only build the released plugin, whereas validation might require more than one locally-built plugin.
For example, when releasing `k8saudit` we build only that plugin in release mode, however when validating with local packages we need Falco to load both `k8saudit` and `json` (because the k8s audit ruleset requires `json` too), and so we need to build a dev package for `json` on the fly.
> fix(ci): build temporary plugins required for release-time validation

- docs/best-practices.md
- plugins/cloudtrail/Makefile
- plugins/cloudtrail/README.md
- plugins/dummy/Makefile
- plugins/dummy_c/README.md
- plugins/gcpaudit/Makefile
- plugins/github/Makefile
- plugins/json/Makefile
- plugins/k8saudit-eks/Makefile
- plugins/k8saudit/Makefile
- plugins/okta/Makefile
- plugins/okta/README.md
/kind cleanup
Supposedly fixes the following error from CodeQL C++:
```
fatal error: cgocheck > 1 mode is no longer supported at runtime. Use GOEXPERIMENT=cgocheck2 at build time instead.
```
> fix(plugins): avoid using gocheck=2

- .github/workflows/reusable_validate_plugins.yaml
/kind bug
/kind cleanup
/area build
In the validation workflow, if/when building plugins on the fly, we currently hit an error like:
```
error obtaining VCS status: exit status 128
Use -buildvcs=false to disable VCS stamping.
```
> fix(ci): solve VCS stamping issues in validation workflow

- plugins/gcpaudit/plugin/plugin.go
/kind cleanup
/area plugins
This should fix up the CI.
> fix(plugins/gcpaudit): properly import gcpaudit package

- plugins/gcpaudit/pkg/gcpaudit/extract.go
> feat(plugins/gcp): extract more gcp fields

- .github/workflows/upload-oci-artifacts.yaml
/kind bug
/area build
In Bash, `echo "something=$(failing_command)"` does not fail. Meaning, if there is an error the job would attempt to continue and mysteriously fail later on. This fixes it.
Fixes #
> fix(gha): catch registry update errors during OCI updates

- build/registry/pkg/oci/oci.go
/kind bug
/area build
Not all rulesfile that have a `rules_url` have an OCI repository for rules that is called `<plugin_name>-rules`. In that case, do not halt the build process but proceed and emit a warning instead.
I believe the proper fix for this would be to remove this job entirely and integrate it with release but we have more cleanups to do before we can do that. In the meantime, this should unblock the current release.
Fixes #
> fix(build): do not halt the build on missing rules repository

- plugins/cloudtrail/pkg/cloudtrail/interval.go
- plugins/cloudtrail/pkg/cloudtrail/source.go
Use the correct format for generating start and stop times.
/kind bug
> /kind design
/area plugins
> /area build
Fixes a time formatting bug in the CloudTrail plugin.
Fixes #
> fix(plugins/cloudtrail): Generate the correct interval values

- registry.yaml
/kind feature
/area registry
GCPaudit is the last addition to our collection. The released version is already signed. This adds the relevant metadata.
This PR also acts as a test for the update job. The bot is supposed to automatically update the index but it did not look like it was triggering so I'm triggering this job to investigate. I believe there may be a Golang version mismatch which I'm going to fix in test-infra.
Fixes #
> new(registry): add signature for gcpaudit

- registry.yaml
/kind feature
/area registry
As per title, since the previous change worked fine :)
Fixes #
> update(registry): add signature info for all official plugins

- plugins/k8saudit/rules/k8s_audit_rules.yaml
/kind feature
/area plugins
Currently there aren't any detections for port forwarding, which isn't great. Port forwarding can be used to avoid controls such as service meshes, and can be used for data exfiltration. There's rarely a good reason for anyone to be using these regularly so it should have a detection, just like exec already does.
For anyone wondering, you can only port forward a pod. When you kubectl port forward svc/myservice it actually checks the selectors for the service and port mapping, and port forwards one of the pods which matches those selectors, on the required port after mapping through the service. This is why I'm only reporting the pod that …
> feat(plugins/k8saudit/rules) add detection for portforwarding

- plugins/k8smeta/src/plugin.cpp
/kind bug
/kind cleanup
/area plugins
This PR removes a wrong log. See the comment to understand why the log is wrong
> update(k8smeta): remove a wrong log

- plugins/k8smeta/README.md
- plugins/k8smeta/cmake/modules/libs.cmake
- plugins/k8smeta/falco.yaml
- plugins/k8smeta/src/grpc_client.cpp
- plugins/k8smeta/src/grpc_client.h
- plugins/k8smeta/src/plugin.cpp
- plugins/k8smeta/src/plugin.h
- plugins/k8smeta/src/shared_with_tests_consts.h
- plugins/k8smeta/test/README.md
- plugins/k8smeta/test/include/k8smeta_tests/helpers.h
- plugins/k8smeta/test/rules/example_rule.yaml
- plugins/k8smeta/test/src/init_config.cpp
/kind cleanup
/area plugins
This PR improves logs and renames some fields for the `k8smeta` plugin. Please note that renaming from `nodename` to `nodeName` is a breaking change!
Please note that renaming from `nodename` to `nodeName` is a breaking change!
> update(k8smeta)!: improve logs and rename some fields

- plugins/okta/CHANGELOG.md
- plugins/okta/README.md
- plugins/okta/pkg/okta/okta.go
/kind bug
/kind cleanup
> /kind design
/kind feature
/area plugins
> /area build
This PR introduces a new parameter `refresh_interval` to avoid `Too many requests` from the Okta API. It also introduces a deduplication of the keys to count the MFA attempts.
Fixes #
> add refresh_interval parameter

- plugins/gcpaudit/rules/gcp_auditlog_rules.yaml
/kind cleanup
/area plugins
There were some grammatical errors in the rules themselves. Also some rules output messages were wrong (e.g. it would say "an object was created" when the rule was for deletion). I also separated some rules into two rules - in particular I tried to create "delete" and "modify" rules separately since I think admins would prefer to have more specificity in their output. 
Fixes #391 
> General rules clean up

- plugins/k8saudit-eks/CHANGELOG.md
- plugins/k8saudit-eks/README.md
- plugins/k8saudit-eks/pkg/k8sauditeks/k8sauditeks.go
/kind bug
> /kind design
/area plugins
> /area build
AWS Cloudwatch Logs truncates log lines with more than 10,000 characters, as these lines can't be parsed by the plugin they are now ignored.
#297 
Fixes #
> ignore truncated lines to avoid parsing errors

- build/registry/pkg/common/consts.go
- build/registry/pkg/oci/requirements.go
> /kind bug
> /kind design
/kind feature
/area plugins
/area build
Find more details here https://github.com/falcosecurity/falco/pull/2899
Fixes #
> update: plugin rules contains a semver required engine version and also new artifacts config layer

- plugins/k8smeta/src/plugin.cpp
/kind bug
/area plugins
This PR moves logs after logger initialization
> fix: move a log after verbosity initialization

- build/registry/pkg/oci/oci.go
/kind bug
/area build
The remote build would show erratic behavior when a 0.10.0 tag was introduced. This was possibly due to git ordering of tags. Instead of relying on it we'll use a set, remove what we don't need and later sort with semver.
Fixes #
> fix(ci): fix remote tag deletion/skipping

- plugins/cloudtrail/pkg/cloudtrail/cloudtrail.go
- plugins/cloudtrail/rules/aws_cloudtrail_rules.yaml
- plugins/dummy/pkg/dummy/dummy.go
- plugins/gcpaudit/pkg/gcpaudit/gcpaudit.go
- plugins/gcpaudit/rules/gcp_auditlog_rules.yaml
- plugins/github/pkg/github/github.go
- plugins/github/rules/github.yaml
- plugins/k8saudit-eks/pkg/k8sauditeks/k8sauditeks.go
- plugins/k8saudit/pkg/k8saudit/k8saudit.go
- plugins/k8saudit/rules/k8s_audit_rules.yaml
- plugins/okta/rules/okta_rules.yaml
/kind feature
/area plugins
After #373 was merged every plugin with rules needs a version bump because OCI rules will not be able to be followed in Falco versions < 0.37.0 (to be released this month). This PR bumps every version. Specifically:
* k8saudit-0.7.0
* cloudtrail-0.10.0
* dummy-0.10.0
* github-0.7.0
* gcpaudit-0.3.0
* k8saudit-eks-0.4.0
This ensures we do not break existing downloads and follows for older Falco versions
Fixes #
> chore(plugins): bump versions for Falco 0.37.0

- registry.yaml
> /kind bug
> /kind design
/kind feature
/area plugins
> /area build
Falco plugin providing basic runtime threat detection and auditing logging for Box.  Because Falco can perform threat detection across a number of cloud platforms in parallel, it allows you to correlate security events across multiple sources in real-time, to detect active lateral movement as it is occurring.
> Registering Box plugin in registry.yaml

- build/registry/go.mod
- build/registry/pkg/oci/requirements.go
- build/registry/pkg/oci/requirements_test.go
- build/registry/pkg/oci/testdata/rules-failed-req.yaml
- build/registry/pkg/oci/testdata/rules-numeric-req.yaml
- build/registry/pkg/oci/testdata/rules-semver-req.yaml
/kind bug
> /kind design
/area build
Properly trim spaces and parse the required engine version. 
Fixes #
> fix(pkg/oci): trim spaces when handling required_engine_version

- plugins/cloudtrail/pkg/cloudtrail/extract.go
> /kind bug
> /kind design
> /area build
Fixes #
> fix: remove s3 notification event extracted fields

- plugins/cloudtrail/README.md
- plugins/cloudtrail/pkg/cloudtrail/extract.go
Adding CloudTrail fields `requestParameters` as `ct.request` and `responseElements` as `ct.response`.
/kind feature
/area plugins
There are too many parameters/elements in `requestParameters`/`responseElements` for all the different API calls to have a dedicated field for every one. Nevertheless, I want to be able to filter or search for the content of these fields in Logray.
This commit provides the entire content of the two fields.
Maybe we can have a 'Custom CloudTrail requestParameters fields' option in Logray (like we have it for 'Custom HTTP Header Fields') in the future. But this needs to be discussed in a separate issue in the Wireshark project.
> feat(cloudtrail): Add ct.response and ct.request field

- plugins/cloudtrail/README.md
- plugins/cloudtrail/pkg/cloudtrail/extract.go
/kind feature
/area plugins
Similar to ct.request, all values should also be available for additionalEventData.
> feat(cloudtrail): Add generic additionalEventData field

- .github/extract-plugins-deps-from-rulesfile.sh
- .github/setup-plugin-config-rules.sh
- .github/workflows/reusable_suggest_rules_version.yaml
- .github/workflows/reusable_validate_plugins.yaml
/kind bug
> /kind design
> /area build
When running the CI for a plugin which is set as an alternative
in the rules files, it is correctly set as a dependency.
Furthermore, the dependency extraction logic from rulesfiles
has been unified for all the use cases and supports multiple
rulesfiles at once.
Fixes #
> fix(CI): correctly extract dependencies for alternatives plugins

- plugins/github/CHANGELOG.md
- plugins/github/pkg/github/extract.go
- plugins/github/pkg/github/github.go
/kind bug
area plugins
Fixes #
> fix(plugins/github): add length check in if statement

- plugins/dummy/pkg/dummy/dummy.go
> /kind bug
> /kind design
> /area build
Fixes #
> chore(dummy): bump version

- .github/workflows/release.yml
- build/utils/version.go
- release.md
> /kind bug
> /kind design
/area build
See #223 
Fixes #223
@falcosecurity/plugins-maintainers Please note that once this PR gets merged, you will need to use the new tag format to release a plugin!
> update(CI): change release tag format

- .github/workflows/registry.yaml
- build/registry/cmd/registry/registry.go
- build/registry/cmd/validateRegistry/validateRegistryFile.go
- build/registry/pkg/oci/const.go
- build/registry/pkg/oci/oci.go
Before adding an entry to the registry.yaml file we check that the OCI artifact for that entry has been released.
> /kind bug
> /kind design
> /area build
Before adding an entry to the registry.yaml file we check that the OCI artifact for that entry has been released.
Fixes #
> new(CI): add registry.yaml validator

- plugins/k8saudit/CHANGELOG.md
- plugins/k8saudit/pkg/k8saudit/k8saudit.go
- plugins/k8saudit/rules/k8s_audit_rules.yaml
/kind bug
> /kind design
/kind feature
/area plugins
> /area build
k8saudit ruleset is only detecting create/delete events for `ClusterRoleBinding` objects. As the rules do detect the create/delete events for `Role` objects, it makes sense to detect create/delete events for `RoleBinding` objects as well.
As `Role` and `RoleBinding` are namespace scoped objects, I did split the rules out for each individual rbac object to include the namespace field into the output. As well as to …
> fix(plugins/k8saudit/rules): split rbac rules by individual rbac object

- .github/workflows/codeql-analysis.yml
> /kind bug
> /kind design
/area build
CodeQL Action v1 was deprecated on January 18th, 2023. This older version seems to fail detecting the golang toolchain directive correctly in go.mod.
Fixes #
> ci: bump CodeQL to v3

- plugins/cloudtrail/pkg/cloudtrail/cloudtrail.go
- plugins/dummy/pkg/dummy/dummy.go
- plugins/gcpaudit/pkg/gcpaudit/gcpaudit.go
- plugins/github/pkg/github/github.go
- plugins/k8saudit/pkg/k8saudit/k8saudit.go
- plugins/kafka/pkg/kafka/kafka.go
/kind bug
/area plugins
As per title. Some plugins have recently been released with a GLIBC version too high, leading to issues like
```
can't load plugin dynamic library: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /usr/share/falco/plugins/libk8saudit.so)
```
The CI has been updated to fix it and now a release is required.
Fixes #
> chore(plugins): bump versions

- plugins/okta/pkg/okta/okta.go
/kind feature
/area plugins
Fixes #
> feat(plugins/okta): introduce optional UseAsync field in okta plugin

- plugins/gcpaudit/CHANGELOG.md
- plugins/gcpaudit/pkg/gcpaudit/config.go
- plugins/gcpaudit/pkg/gcpaudit/gcpaudit.go
/kind feature
/area plugins
Fixes #
> feat(plugins/gcpaudit): introduce optional UseAsync field in gcpaudit plugin

- plugins/cloudtrail/pkg/cloudtrail/cloudtrail.go
- plugins/cloudtrail/pkg/cloudtrail/extract.go
Generalize our array length check. Use strings.TrimSuffix in order to avoid a potential string under-read.
> /kind bug
/kind cleanup
> /kind design
/area plugins
> /area build
Fixes #
> update(cloudtrail): Update ct.resources handling

- plugins/k8smeta/README.md
- plugins/k8smeta/falco.yaml
- plugins/k8smeta/src/grpc_client.cpp
- plugins/k8smeta/src/plugin.cpp
- plugins/k8smeta/src/plugin.h
- plugins/k8smeta/src/shared_with_tests_consts.h
- plugins/k8smeta/test/README.md
- plugins/k8smeta/test/include/k8smeta_tests/helpers.h
- plugins/k8smeta/test/src/check_events.cpp
- plugins/k8smeta/test/src/init_config.cpp
- plugins/k8smeta/test/src/parsing_pod.cpp
/kind bug
/kind feature
/area plugins
This PR introduces a proc-scan feature in the k8smeta plugin init phase. We need this to collect the pod uid of threads already running when Falco and the k8smeta plugin are started. 
Fixes #https://github.com/falcosecurity/plugins/issues/514
> fix(k8smeta): introduce /proc scan to recover the pod uid of threads already spawned

- registry.yaml
/kind feature
/area registry
Introduced a new Falco plugin with source and extractor capabilities for Keycloak user/admin events.
Fixes #
> feat: Added keycloak plugin to registry.yaml

- plugins/k8saudit/rules/k8s_audit_rules.yaml
/kind bug
/area plugins
This rule has an issue where it detects a configmap that seems to contain confidential information, but still outputs its content. For example, the content could potentially be notified to Slack. Therefore, it would be better not to output the object's content in this case.
Fixes #
> fix:Do not output information that contains confidential data.

- .github/workflows/reusable-publish-oci-artifacts.yaml
- .github/workflows/reusable_build_packages.yaml
- .github/workflows/reusable_build_rules_tool.yaml
- .github/workflows/reusable_publish_packages.yaml
- .github/workflows/reusable_suggest_rules_version.yaml
- .github/workflows/reusable_validate_plugins.yaml
> /kind bug
> /kind design
/kind feature
/area build
Artifact actions v3 will be deprecated by December 5, 2024
Fixes #
> ci: upgrade artifact actions

- plugins/k8smeta/src/plugin.cpp
- plugins/k8smeta/test/src/parsing_pod.cpp
By scanning only /proc we missed the threads of a given process. It scans all threads under a given process in /proc/pid/task.
/kind bug
> /kind design
/area plugins
> /area build
By scanning only /proc we missed the threads of a given process.
It scans all threads under a given process in /proc/pid/task.
Fixes #
> fix(proc/scan): scan all existing threads

- plugins/k8smeta/src/plugin.cpp
/kind bug
> /kind design
/area plugins
> /area build
`std::filesystem::directory_iterator` works by retrieving entries on the fly as it iterates over them,
rather than preloading all entries. This implies that entries could indeed disappear (or appear)
between iterations, especially in highly dynamic directories such as `/proc/`.
The loop continues processing other entries even if an exception occurs,
allowing for robust and uninterrupted iteration.
**Which issue(s) …
> fix(k8smeta): handle missing directories/files during /proc scan

- plugins/gcpaudit/README.md
- plugins/gcpaudit/pkg/gcpaudit/extract.go
- plugins/gcpaudit/pkg/gcpaudit/gcpaudit.go
/kind feature
/area plugins
On the GCP Plugin we already expose the resource type via the `gcp.resourceType` field. Given that the log-entry also supports a `labels` field which can contains useful information for correctly identifying a resource on GCP, we want to expose that using a new `gcp.resourceLabels` field.
This field will contain the JSON representation of the labels attached on the [cloud log entry.](https://cloud.google.com/logging/docs/reference/v2/rest/v2/MonitoredResource)
Fixes #
> Expose gcp.resourceLabels field in the gcp plugin

- plugins/k8saudit/rules/k8s_audit_rules.yaml
/kind bug
> /kind design
/area plugins
> /area build
I discovered the `exec` in pod in EKS are not firing alert with the current rules for `k8s_audit` sources.
It comes from the `verb` which is not correct in the current rule. The condition expects `ka.verb = create` but for EKS it's `get`. The issue might be there for other managed cluster.
Here's an example of audit log from EKS for example:
```json
{
"kind": "Event",
"apiVersion": "audit.k8s.io/v1",
"level": …
```
> fix the rule to detect the exec in EKS

- .github/dependabot.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/create-comment.yaml
- .github/workflows/dummy_c-ci.yaml
- .github/workflows/k8smeta-ci.yaml
- .github/workflows/main.yaml
- .github/workflows/release.yml
- .github/workflows/reusable-publish-oci-artifacts.yaml
- .github/workflows/reusable_build_packages.yaml
- .github/workflows/reusable_build_rules_tool.yaml
- .github/workflows/reusable_get_changed_plugins.yaml
- .github/workflows/reusable_publish_packages.yaml
- .github/workflows/reusable_suggest_rules_version.yaml
- .github/workflows/reusable_upload_pr_info.yaml
- .github/workflows/reusable_validate_plugins.yaml
/kind cleanup
/area build
Update ci / add dependabot 
/assign @jasondellaluce @leogr @LucaGuerra 
xref: https://github.com/falcosecurity/evolution/issues/339
```release-note
Update ci / add dependabot
```
> clean up update ci and add dependabot config

- plugins/k8saudit-eks/pkg/k8sauditeks/k8sauditeks.go
- plugins/k8saudit-gke/pkg/k8sauditgke/k8sauditgke.go
- plugins/k8saudit/pkg/k8saudit/k8saudit.go
- plugins/k8saudit/rules/k8s_audit_rules.yaml
/kind bug
> /kind design
/kind feature
/area plugins
> /area build
Fixes #
> bulk k8saudit plugins update

- build/registry/pkg/oci/oci.go
This is required as a consequence of the falcoctl v0.11 upgrade.
/kind bug
> /kind design
> /area build
Fixes #
> fix(build/registry): switch to RootDigest

- plugins/cloudtrail/pkg/cloudtrail/cloudtrail.go
- plugins/cloudtrail/pkg/cloudtrail/source.go
/kind cleanup
/kind feature
/area plugins
Some pre-ControlTower organization Cloutrail trails are missing the OrgId in the AWSLogs S3 path. Making the OrgId optional gives them the option to use S3AccountList.
> update(plugins/cloudtrail): support pre-ControlTower organization trails

- .github/workflows/ci.yaml
- .github/workflows/main.yaml
- .github/workflows/release.yml
- plugins/k8smeta/README.md
- plugins/k8smeta/cmake/modules/libs.cmake
- plugins/k8smeta/cmake/modules/plugin-sdk-cpp.cmake
- plugins/k8smeta/src/plugin.cpp
- plugins/k8smeta/src/plugin.h
- plugins/k8smeta/src/shared_with_tests_consts.h
- plugins/k8smeta/test/src/check_events.cpp
- plugins/k8smeta/test/src/parsing_pod.cpp
/kind cleanup
/kind feature
/area plugins
Implemented the "suggested output fields feature", by suggesting `k8smeta.pod.name` and `k8smeta.ns.name` as output fields.
Also, entirely avoid the proc scan, instead relying on the listening CAPability to initially loop over the thread table to attach pod_uid to threads.
Following the above, `hostProc` initConfig key is now deprecated and unused.
Moved the plugin to 0.3.0 too (given the minimum plugin API version changes).
Fixes #
> new(plugins/k8smeta): update k8smeta plugin to require plugin API version 3.9.0.

- plugins/container/Makefile
- plugins/container/README.md
- plugins/container/go-worker/pkg/config/config.go
- plugins/container/go-worker/pkg/container/containerd.go
- plugins/container/go-worker/pkg/container/cri.go
- plugins/container/go-worker/pkg/container/docker.go
- plugins/container/go-worker/pkg/container/podman.go
- plugins/container/src/macros.h
- plugins/container/src/plugin_config.cpp
- plugins/container/src/plugin_config.h
- plugins/container/src/plugin_config_schema.h
- plugins/container/test/config.cpp
/kind feature
/area plugins
Some fields (namely IP address for docker engine) are not available at `Create` hook. Allow user to specify which hooks to attach.
By default, we only attach `Create` hook since we can be sure that it is called way before the container gets started, thus it gives us time to retrieve metadata before the first process starts.
If both hooks are attached, you'll get doubled "container" events, and a single "container_removed" event.
Fixes #
> new(plugins/container): allow to specify which hook to be attached between {"create", "start"}

- registry.yaml
> /kind bug
> /kind design
> /area build
Just a documentation change, there was mention AKS being related with AWS.
Fixes #
> docs: fix incorrect cloud provider reference (AWS → Azure) for AKS

- plugins/container/src/caps/async/async.cpp
/kind bug
/area plugins
#715  loaded pre-existing containers and then copied them to the containers cache; doing so, it was overriding the `""` (empty) key, that is used for host container info.
Fixes #
> fix(plugin/container): avoid overwriting host container info when loading pre-existing containers

- plugins/container/go-worker/pkg/container/containerd_test.go
- plugins/container/go-worker/pkg/container/cri.go
- plugins/container/go-worker/pkg/container/cri_test.go
- plugins/container/go-worker/pkg/container/docker_test.go
- plugins/container/go-worker/pkg/container/fetcher_test.go
- plugins/container/go-worker/pkg/container/podman_test.go
/kind bug
/kind cleanup
/area plugins
Also, fixed a small bug in cri engine `get()` method.
Fixes #
> new(plugins/container): added fetcher tests.

- plugins/container/src/caps/extract/extract.cpp
/kind feature
/area plugins
Suggest more output fields for container plugin.
Specifically:
* `%container.image.repository`
* `%container.image.tag`
* `%k8s.ns.name`
* `%k8s.pod.name`
This will allow us to deprecated (and drop) `-pc` and `-pk` Falco CLI flags: https://github.com/falcosecurity/falco/blob/master/userspace/falco/app/actions/init_falco_engine.cpp#L97
Fixes #
> new(plugins/container): suggest more output fields.

- build/readme/fields.go
- plugins/krsi/README.md
- plugins/krsi/krsi/src/lib.rs
> /kind bug
> /kind design
/area plugins
> /area build
This PR adds support for automatic generation of `krsi` plugin's field extraction. Moreover, it adds support for handling multi-line field extraction descriptions.
Fixes #
> doc: add support for `krsi` plugin field extraction doc auto-gen

- plugins/container/go-worker/pkg/container/fetcher.go
/kind bug
/area plugins
Podman relies upon context to store its connection infos. Using same ctx already used by the real Podman engine means that we are going to tamper with its connection info stored in the main ctx.
Instead, fetcher should use its own context.
Fixes #
> fix(plugins/container): use an unique ctx for fetcher.

- plugins/krsi/krsi-ebpf/src/auxmap.rs
/kind bug
> /kind design
/area plugins
> /area build
This PR fixes the eBPF event submission by only sending the interesting payload, instead of sending the entire auxiliary map buffer.
Fixes #
> fix(plugins/krsi/krsi-ebpf): send only interesting payload

- plugins/krsi/krsi-ebpf/src/auxbuf.rs
- plugins/krsi/krsi-ebpf/src/main.rs
- plugins/krsi/krsi-ebpf/src/operations/bind.rs
- plugins/krsi/krsi-ebpf/src/operations/connect.rs
- plugins/krsi/krsi-ebpf/src/operations/linkat.rs
- plugins/krsi/krsi-ebpf/src/operations/mkdirat.rs
- plugins/krsi/krsi-ebpf/src/operations/open.rs
- plugins/krsi/krsi-ebpf/src/operations/renameat.rs
- plugins/krsi/krsi-ebpf/src/operations/socket.rs
- plugins/krsi/krsi-ebpf/src/operations/symlinkat.rs
- plugins/krsi/krsi-ebpf/src/operations/unlinkat.rs
> /kind bug
/kind cleanup
> /kind design
/area plugins
> /area build
This PR removes the dependency of auxbuf on the ring buffer.
Fixes #
> refactor(plugins/krsi/krsi-ebpf): remove auxbuf dep on ringbuf

- plugins/krsi/Cargo.lock
- plugins/krsi/Cargo.toml
- plugins/krsi/krsi-common/Cargo.toml
- plugins/krsi/krsi-common/src/lib.rs
- plugins/krsi/krsi-ebpf/Cargo.toml
- plugins/krsi/krsi-ebpf/src/auxbuf.rs
- plugins/krsi/krsi/Cargo.toml
- plugins/krsi/krsi/src/krsi_event.rs
> /kind bug
/kind cleanup
/kind design
/area plugins
> /area build
This PR removes unsafe code from `auxbuf` by using `zerocopy` crate to perform conversions between bytes and structs as well as unaligned read and write operations.
Fixes #
> refactor(plugins/krsi): remove `auxbuf` unsafe code using `zerocopy`

- plugins/krsi/krsi-ebpf/src/auxbuf.rs
- plugins/krsi/krsi-ebpf/src/main.rs
- plugins/krsi/krsi-ebpf/src/operations/bind.rs
- plugins/krsi/krsi-ebpf/src/operations/connect.rs
- plugins/krsi/krsi-ebpf/src/operations/linkat.rs
- plugins/krsi/krsi-ebpf/src/operations/mkdirat.rs
- plugins/krsi/krsi-ebpf/src/operations/open.rs
- plugins/krsi/krsi-ebpf/src/operations/renameat.rs
- plugins/krsi/krsi-ebpf/src/operations/socket.rs
- plugins/krsi/krsi-ebpf/src/operations/symlinkat.rs
- plugins/krsi/krsi-ebpf/src/operations/unlinkat.rs
- plugins/krsi/krsi-ebpf/src/operations/writer_helpers.rs
> /kind bug
/kind cleanup
/kind design
/area plugins
> /area build
This PR replaces the usage of offsets with slices in `auxbuf`. This enables better compile-time checks thanks to the language native support for slice types.
In order to restore a previous auxbuf writer state, the user must now first cache its state using the `Writer::save()` and `AuxiliaryBuffer::save_writer_state()` APIs; then it can restore it using the `AuxiliaryBuffer::resume_writer()` API.
Moreover, it makes …
> refactor(plugins/krsi/krsi-ebpf): use slices in auxbuf code

- plugins/container/CMakeLists.txt
- plugins/container/go-worker/pkg/container/docker.go
- plugins/container/go-worker/pkg/container/engine.go
- plugins/container/go-worker/pkg/container/engine_test.go
- plugins/container/go-worker/pkg/container/podman.go
- plugins/container/go-worker/pkg/event/event.go
/kind bug
> /kind design
/area plugins
> /area build
This PR redefines port binding's port and IP as integers.
Fixes #814 
> fix(plugins/container): redefine port binding port and IP as integers

- plugins/container/CMakeLists.txt
- plugins/container/src/container_info_json.cpp
- plugins/container/test/container_info_json.cpp
/kind bug
/area plugins
When healthcheck `args` key exists but is `null` the container plugin raises an exception.
While at it, i also added a test case for this.
Fixes #
> fix(plugins/container): avoid crash when healthcheck probe args is null

- plugins/container/src/caps/async/async.tpp
- plugins/container/src/caps/parse/parse.cpp
- plugins/container/src/container_info.h
- plugins/container/src/container_info_json.cpp
- plugins/container/src/container_info_json.h
- plugins/container/src/container_type.h
- plugins/container/src/matchers/bpm.cpp
- plugins/container/src/matchers/bpm.h
- plugins/container/src/matchers/libvirt_lxc.cpp
- plugins/container/src/matchers/libvirt_lxc.h
- plugins/container/src/matchers/lxc.cpp
- plugins/container/src/matchers/lxc.h
- plugins/container/src/matchers/matcher.cpp
- plugins/container/src/matchers/matcher.h
- plugins/container/src/matchers/static_container.cpp
- plugins/container/src/matchers/static_container.h
- plugins/container/src/plugin.cpp
- plugins/container/src/plugin.h
- plugins/container/test/container_info_json.cpp
- plugins/container/test/matchers.cpp
/kind cleanup
/area plugins
Headers cleanup in the container plugin
Fixes #
> chore(plugins/container): headers cleanup

- plugins/container/CMakeLists.txt
- plugins/container/src/caps/parse/parse.cpp
- plugins/container/src/consts.h
- plugins/container/src/macros.h.in
- plugins/container/src/plugin.h
/kind bug
/area plugins
Normally, we receive "removed" events from the container runtime; but that's not the case for libvirt-lxc, lxc and bpm.
In these cases, properly cleanup container cache upon init_container process exiting.
Fixes #
> fix(plugins/container): properly cleanup stale container cache entries for exiting containers

- shared/go/aws/cloudwatchlogs/cloudwatch.go
/kind bug
/area plugins
Cloudwatch events can have the same timestamp but different IngestionTime, making the logic of polling with `filters.SetStartTime(lastEventTime + 1)` flawed against these late events.
The idea here is to query again the events from the `lastEventTime` and filter out any duplicates. This shouldn't have a relevant performance penalty since the number of events with the same timestamp is very small compared to the number of events fetched when the polling interval is in the order of seconds.
[According to the AWS docs for `FilterLogEvents`](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_FilterLogEvents.html):
> The …
> fix(plugins/k8saudit-eks): Improve handling of events with the same timestamp
