README.md
=> docs(README.md): notice regarding the project status

.github/PULL_REQUEST_TEMPLATE.md
Add the PR template.
```release-note
NONE
```
=> docs(.github): add pull request template

plugins/cloudtrail/README.md
Add a README for the cloudwatch plugin, which documents the fields,
plugin config, open params, and ways the plugin can fetch cloudtrail
events.
> /kind bug
> /kind design
> /area source-plugins
> /area build
Fixes #
```release-note
NONE
```
=> Add README for cloudwatch plugin

plugins/cloudtrail/cloudtrail.go
The biggest driver for this is to ensure that a user can write a
clause "and not ct.error exists" and have the clause evaluate to true
if there is no error. Previously, ct.error would return an empty
string, which still counted as "existing".
Instead of converting missing fields in the json object to "", be more
strict about missing fields:
- In Next(), if the eventTime or eventType are missing, skip the event
by returning timeout.
- In getUser(), change the return value to (present, user) and set
present to false if userIdentity is missing or if the code can't
identify a user. In get_fields() for ct.user, set field_present to
false if getUser()'s present is false. In event_to_string, use a
blank string for the user if not present.
- In event_to_string, if eventSource, awsRegion, or …
=> Be more strict about missing fields

plugins/cloudtrail/README.md, plugins/cloudtrail/cloudtrail.go
Add fields to the cloudtrail plugin to match former `json.value[...]` fields in the initial cloudtrail ruleset.
This should wait for #12 to merge first--this was based on those changes and will need a rebase.
> /kind bug
> /kind design
/kind feature
> /area build
Fixes #
```release-note
NONE
```
=> Add addl fields

plugins/cloudtrail/cloudtrail.go, plugins/json/json.go
Update plugin contact url for cloudtrail/json plugins to their
official repo.
> /kind bug
> /kind design
/area extractor-plugins
> /area build
Fixes #
```release-note
NONE
```
=> Update plugin contact

plugins/PLUGINS-REGISTRY.md
It's "aws_cloudtrail" at the moment, not "cloudtrail".
> /kind bug
> /kind design
> /area source-plugins
> /area build
Fixes #
```release-note
NONE
```
=> Fix event source for cloudtrail plugin

sdk/cpp/falcosecurity_plugin.h
The old version didn't save any intermediate string result for later
use. Also, add a good description to the method so potential plugin
authors know what the returned values should be.
> /kind bug
/kind cleanup
> /kind design
> /area build
Fixes #
```release-note
NONE
```
=> Add better support for read_progress to c++ sdk

Makefile, plugins/cloudtrail/cloudtrail.go, plugins/dummy/dummy.go, plugins/dummy_c/dummy.cpp, plugins/json/json.go
/kind design
/kind feature
/area extractor-plugins
/area build
This includes the platform in the name of plugins artifacts for both pre-release and release builds. Accordingly, the version of all plugins has been bumped to trigger a rebuild.
```release-note
build: add cross-platform support to plugins artifacts
```
=> build: add cross-platform support to plugins artifacts

registry.yaml
/kind cleanup
This fixes a spacing issue in the plugin registry, and we can use it to test the new post-submit CI jobs.
=> chore(registry): fix spacing issues

Makefile, build/registry/table.go, build/registry/types.go, plugins/cloudtrail/Makefile, plugins/cloudtrail/cloudtrail.go, plugins/cloudtrail/extract.go, plugins/cloudtrail/source.go, plugins/dummy/Makefile, plugins/dummy/dummy.go, plugins/dummy_c/Makefile, plugins/dummy_c/dummy.cpp, plugins/json/Makefile, plugins/json/json.go, registry.yaml
/kind feature
/area plugins
/area registry
This adds a field for licenses in the plugin registry. The registry tool is updated with minor aesthetic changes, and now supports plugin licenses too. The license of all the plugins in the repo has been updated/added.
=> update: update plugins license, add license to registry and add aesthetic changes

Makefile, README.md, build/registry/registry.go, build/registry/table.go
/kind cleanup
/area registry
This documents the contents of the repo and the plugin registry inside the README. The registry tool has been improved accordingly.
=> docs: fully-document readme and improve registry tool

README.md
Signed-off-by: Federico Di Pierro <nierro92@gmail.com>
> /kind bug
/kind cleanup
> /kind design
> /area build
Fixes #
=> chore(readme): updated links pointing to falco doc.

registry.yaml
Signed-off-by: Issif <issif+github@gadz.org>
> /kind bug
> /kind design
/kind feature
/area plugins
> /area build
This PR proposes [`docker plugin`](https://github.com/Issif/docker-plugin) as new plugin
Fixes #
=> register new plugin for Docker

registry.yaml
Signed-off-by: Alban Crequy <albancrequy@microsoft.com>
> /kind bug
> /kind design
/kind feature
/area plugins
> /area build
This PR proposes [a seccomp agent plugin](https://github.com/kinvolk/seccompagent) as new plugin
Fixes #
* I used ID 6 because ID 5 will be used by https://github.com/falcosecurity/plugins/pull/69
* The plugin code at https://github.com/falcosecurity/plugins/pull/69 is not yet merged, so …
=> register new plugin for Seccomp Agent

plugins/json/json.go, plugins/json/json_test.go
/kind bug
/kind feature
/area plugins
This PR adds unit tests to the `json` plugin, with which we were able to discover and fix a bug in the JSON Pointer support. With this, we reach a test coverage of ~80% of statements.
Fixes #
=> update(plugins/json): fix json pointer support and add unit tests

.github/workflows/codeql-analysis.yml, plugins/okta/LICENSE, plugins/okta/Makefile, plugins/okta/README.md, plugins/okta/go.mod, plugins/okta/go.sum, plugins/okta/main.go, registry.yaml
Signed-off-by: Issif <issif+github@gadz.org>
> /kind bug
> /kind design
/kind feature
/area plugins
> /area build
This add sources and register for a new plugin for Okta Log Events
Fixes #
=> register new plugin for Okta

plugins/k8saudit/.gitignore, plugins/k8saudit/Makefile, plugins/k8saudit/extract.go, plugins/k8saudit/go.mod, plugins/k8saudit/go.sum, plugins/k8saudit/pkg/k8saudit/extract.go, plugins/k8saudit/pkg/k8saudit/extract_test.go, plugins/k8saudit/pkg/k8saudit/fields.go, plugins/k8saudit/pkg/k8saudit/source.go, plugins/k8saudit/plugin.go, plugins/k8saudit/source.go, registry.yaml
/kind feature
/area plugins
/area registry
This PR is part of the ongoing effort of porting the current K8S Audit Log implementation bundled in Falco as a falcosecurity plugin. Here, we implement the K8S Audit source and extraction from scratch using the Plugin SDK Go. 
=> new(plugins): k8s audit log plugin porting

plugins/k8saudit/pkg/k8saudit/extract.go
/kind bug
/kind cleanup
/area plugins
This PR polishes the `k8saudit` plugin to fix some errors and better align its implementation with the legacy one implemented inside Falco.
=> update(plugins/k8saudit): bug fixes, code polishing, better alignment with legacy implementation

Makefile
> /kind bug
> /kind design
/kind feature
/area build
Currently, WIP
Fixes #
=> build: rules releases

Makefile
> /kind bug
/kind cleanup
> /kind design
/area build
Fixes #
=> chore(Makefile): remove leftover

plugins/k8saudit/README.md
/area plugins
This adds a README file in the k8saudit plugin.
=> docs(plugins/k8saudit): add readme

docs/best-practices.md
> /kind bug
/kind cleanup
> /kind design
> /area build
Fixes #
=> docs: best practices - directory layout

README.md
Updating README.md (automatically generated with build/registry). Made using the [build-plugins-update-readme-postsubmit](https://github.com/falcosecurity/test-infra/blob/master/config/jobs/build-plugins/build-plugins.yaml) ProwJob. Do not edit this PR.
=> docs(README.md): update plugin registry table

plugins/k8saudit/go.mod, plugins/k8saudit/go.sum, plugins/k8saudit/pkg/k8saudit/config.go, plugins/k8saudit/pkg/k8saudit/k8saudit.go, plugins/k8saudit/pkg/k8saudit/source.go, plugins/k8saudit/plugin/k8saudit.go
/kind bug
/kind feature
/area plugins
This PR solves some issues with the k8saudit plugin, mostly related to error reporting. At the same time, this experiments using the newest fixes in the Go SDK.
=> fix(plugins/k8saudit): solve k8saudit issues and improve error reporting

plugins/cloudtrail/README.md
Signed-off-by: lucas.teixeira <lucas.teixeira@ifood.com.br>
> /kind bug
> /kind design
> /area build
**What this PR does / why we need it**: Updates the documentation with needed information to make it run smoothly.
**Which issue(s) this PR fixes**: The `json` plugin is needed with the `cloudtrail` plugin in order to interpret the rules established on the `aws_cloudtrail_rules.yaml`. Also, the plugin expects the logs to be compressed (.gz file) as it can't read plain JSON files.
Fixes # …
=> Update cloudtrail plugin doc

plugins/okta/go.mod, plugins/okta/go.sum, plugins/okta/pkg/okta/okta.go, plugins/okta/plugin/okta.go
/kind bug
> /kind design
/kind feature
/area plugins
> /area build
Just a follow-up of https://github.com/falcosecurity/plugins/pull/112.
I forgot `okta`, sorry :sweat_smile: 
Fixes #
=> update(plugins/k8saudit): adapt plugin for plugin-sdk-go v0.4.0

plugins/json/go.mod, plugins/json/go.sum, plugins/json/pkg/json/config.go, plugins/json/pkg/json/json.go, plugins/k8saudit/pkg/k8saudit/k8saudit.go
/kind feature
/area plugins
This PR updates the `json` plugin to accept an init configuration. The configuration allows users to enable/disable the async extraction optimization, which could be helpful for debug and tuning purposes.
=> update(plugins/json): add plugin init configuration

plugins/dummy/CHANGELOG.md
=> update(plugins/dummy): update changelog

Makefile, plugins/cloudtrail/Makefile, plugins/dummy/Makefile, plugins/dummy_c/Makefile, plugins/github/Makefile, plugins/json/Makefile, plugins/k8saudit/Makefile, plugins/okta/Makefile
/kind feature
/area build
This adds support to make `-j` parallelism, which should make the building phase faster.
=> update(makefile): support make parallelism

docs/best-practices.md
> /kind bug
> /kind design
> /area build
Fixes #
=> docs(best-practices): update  URL

docs/best-practices.md, plugins/cloudtrail/pkg/cloudtrail/config.go, plugins/dummy/pkg/dummy/dummy.go, plugins/github/pkg/github/config.go, plugins/json/pkg/json/config.go, plugins/k8saudit/pkg/k8saudit/config.go, plugins/okta/pkg/okta/okta.go
> /kind bug
/kind cleanup
> /kind design
/area plugins
> /area build
This adds titles and default values to the existing plugin configuration parameters. It also adds a note about parameter annotations to the best practices guide.
Fixes #
=> Config schema title default

plugins/cloudtrail/README.md, plugins/cloudtrail/go.mod, plugins/cloudtrail/go.sum, plugins/cloudtrail/pkg/cloudtrail/config.go, plugins/cloudtrail/pkg/cloudtrail/source.go
/kind feature
/area plugins
Adds support for cloudtrail plugin to pull cloudtrail logs from s3 based on s3-event SNS. Further details in issue.  
Fixes #135 
=> feat: parse SNS originating from S3

plugins/k8saudit/rules/k8s_audit_rules.yaml
Signed-off-by: Frank Jogeleit <frank.jogeleit@lovoo.com>
> /kind bug
> /kind design
/kind feature
/area plugins
> /area build
It adds the `ka.target.resource` output to each rule, it's needed in tools like falcosidekick to determine the related k8s resource
.
Fixes #
https://kubernetes.slack.com/archives/CMWH3EH32/p1661367793723389
=> feature(plugins/k8saudit/rules): Add ka.target.resource

plugins/github/README.md
/kind cleanup
This fixes some inaccuracies in the readme of the github plugin, including a broken link.
=> chore(plugins/github): update readme

plugins/cloudtrail/pkg/cloudtrail/cloudtrail.go, plugins/json/pkg/json/json.go, plugins/k8saudit/pkg/k8saudit/k8saudit.go
=> update: bump plugin rc versions

plugins/k8saudit/README.md
> /kind bug
> /kind design
/area plugins
> /area build
Fixes #
=> docs(k8saudit): update README.md

registry.yaml
> /kind bug
/kind cleanup
> /kind design
/kind feature
/area registry
> /area build
Fixes #
=> chore(registry.yaml): dummy change just to trigger the CI

registry.yaml
/kind cleanup
/area registry
Little chore to trigger the CI
=> chore(registry.yaml): dummy in upper case

README.md, build/registry/pkg/registry/validate.go
> /kind bug
/kind design
/area build
Fixes #
=> update metadata constraints

registry.yaml
/kind cleanup
Simple chore to trigger the CI.
Fixes #
=> chore(registry.yaml): triggering the CI

registry.yaml
=> chore(registry.yaml): trigger the CI

plugins/okta/pkg/okta/okta.go
/kind bug
> /kind design
/area plugins
> /area build
Fixes #
=> fix(okta): correct version (release candidate)

shared/go/aws/cloudwatchlogs/cloudwatch.go
Signed-off-by: Thomas Labarussias <issif+github@gadz.org>
> /kind bug
/kind cleanup
> /kind design
/area plugins
> /area build
Replace the iteration over pages by the dedicated function from the SDK
Fixes #
=> Update pagination function for cloudwatch logs

plugins/cloudtrail/pkg/cloudtrail/aws.go
Add a "region" configuration option which lets the user specify an AWS region.
The jsonschema module was truncating descriptions with commas, so remove them for now.
> /kind bug
/kind cleanup
> /kind design
/area plugins
> /area build
A completely unscientific survey of GitHub's search box returned the following:
AWS_PROFILE: 168K code hits, 124 wiki hits  
AWS_DEFAULT_PROFILE: 16K code hits, 13 wiki hits  
AWS_REGION: 643K code hits, 359 wiki hits  
AWS_DEFAULT_REGION: 2M code …
=> update(plugins/cloudtrail): Add a region setting.

changelog-gen.sh, plugins/cloudtrail/CHANGELOG.md, plugins/dummy/CHANGELOG.md, plugins/github/CHANGELOG.md, plugins/json/CHANGELOG.md, plugins/k8saudit-eks/CHANGELOG.md, plugins/k8saudit/CHANGELOG.md, plugins/okta/CHANGELOG.md
/area plugins
Scripts have been updated to avoid counting `-rc` release while generating the changelogs.
=> update: generate readmes

.github/workflows/upload-oci-artifacts.yaml
Signed-off-by: Lorenzo Susini <susinilorenzo1@gmail.com>
> /kind bug
> /kind design
> /area build
Fixes #
=> update: temporarily remove cron job when uploading OCI artifacts

.github/workflows/upload-oci-artifacts.yaml
> /kind bug
> /kind design
> /area build
Fixes #
=> fix cron timer

registry.yaml
Signed-off-by: Lorenzo Susini <susinilorenzo1@gmail.com>
> /kind bug
> /kind design
/area registry
> /area build
This PR is needed to trigger a CI test, see this: https://github.com/falcosecurity/test-infra/pull/873
Fixes #
=> chore: little modification to dummy_c description to test prow CI

build/registry/pkg/registry/distribution/index.go
/kind bug
> /kind design
/area registry
> /area build
Correctly set the repo values for plugin artifacts when generating the index file.
Fixes #
=> fix(oci-registry: correctly set repo value for plugin artifacts

registry.yaml
Signed-off-by: Luca Guerra <luca@guerra.sh>
> /kind bug
/kind cleanup
/area registry
> /area build
Fixes #
=> update(registry): update registry.yaml

plugins/github/pkg/github/extract.go, plugins/github/pkg/github/github.go, plugins/github/pkg/github/miners.go, plugins/github/pkg/github/server.go, plugins/github/pkg/github/source.go, plugins/github/rules/github.yaml
> /kind bug
> /kind design
/kind feature
/area plugins
> /area build
Add fields and rules to detect GitHub actions that include crypto miners
Fixes #
=> Add fields and rules to detect GitHub actions that include crypto miners

plugins/github/rules/github.yaml
Signed-off-by: Loris Degioanni <loris@sysdig.com>
> /kind bug
> /kind design
/kind feature
/area plugins
> /area build
refine the GitHub miner detection rule
the GitHub miner detection rule could have generated multiple detections 
Fixes #
=> refine the GitHub miner detection rule

build/registry/cmd/registry/registry.go, build/registry/pkg/registry/oci/const.go, build/registry/pkg/registry/oci/oci.go
> /kind bug
> /kind design
/area registry
/area build
This PR changes the source of truth used to discover new versions of plugins and rulesfiles. The CI parses the `registry.yaml` file and for each entry:
* Plugins: checks if the plugin entry has already been pushed to the
OCI registry. If found, retrieves the latest version otherwise
do nothing. It checks if there have been released new versions
of the plugin by checking the release tags in the local git repo.
If …
=> update(build/registry) change the logic how new versions of artifacts are discovered

.github/workflows/upload-oci-artifacts.yaml, build/registry/pkg/registry/oci/oci.go
/kind bug
> /kind design
/area build
It could happen that for a given local tag in the git repo there is not a release. We just log a warning and keep going with the other plugins.
Fixes #
=> fix(build/registry): do not error when no archives are found in s3 bucket

.gitignore, build/registry/pkg/registry/oci/const.go, build/registry/pkg/registry/oci/oci.go
> /kind bug
/kind cleanup
> /kind design
/area registry
> /area build
Remove dead code from oci package.
Fixes #
=> chore(ci/cleanup): remove dead code from oci package

build/registry/cmd/registry/registry.go, build/registry/pkg/registry/distribution/index.go
> /kind bug
/kind cleanup
> /kind design
/area registry
/area build
Move the logic that creates/updates `index` file from the main package to the distribution package. This PR aims to better organize the code of the `registry` command.
Fixes #
=> refactor(build/registry): move index logic from main package to distribution package

build/registry/cmd/registry/registry.go, build/registry/pkg/check/check.go
> /kind bug
/kind cleanup
> /kind design
/area registry
> /area build
Move check logic from `main` package to check package.
Fixes #
=>  refactor(build/registry): move check logic from main package to check package

build/registry/cmd/registry/registry.go, build/registry/pkg/table/table.go
> /kind bug
> /kind design
> /area build
Move table command from `main` package to table package.
Fixes #
=>  refactor(build/registry): move table command from main package to table package

build/registry/pkg/oci/oci.go
/kind bug
> /kind design
/area registry
> /area build
The order of the tags affects how the registries' UI shows the info
about an artifact.
For example this is how the GHCR registry shows the tags for an artifact before the fix:
After the fix:
This fix is made possible by: falcosecurity/falcoctl#196
Fixes #
=> fix(ci/registry): push tags for artifacts in correct order 

build/registry/pkg/oci/oci.go
/kind bug
> /kind design
/area registry
> /area build
For a given version of a `rulesfile` check that one and only one archive exists on the `S3 bucket`.
Fixes #
=> fix(build/registry): enforce to one the number of rulesfiles for a given version

build/registry/pkg/common/consts.go, build/registry/pkg/distribution/index.go
/kind bug
> /kind design
/area registry
> /area build
Introduce common package to avoid import cycles in the `registry` tool.
Fixes #
=> chore(build/registry): introduce common package to avoid import cycles

plugins/cloudtrail/rules/aws_cloudtrail_rules.yaml, plugins/github/rules/github.yaml, plugins/k8saudit/rules/k8s_audit_rules.yaml
> /kind bug
> /kind design
/area plugins
> /area build
This PR bumps the `required_plugins_versions` for the following rulesfiles: 
* cloudtrail
* github
* k8saudit
Fixes #
=> bump requirements in rulesfiles

.github/workflows/upload-oci-artifacts.yaml
> /kind bug
> /kind design
/area registry
> /area build
We temporary need to disable the cron job for the CI that uploads artifacts to the registry for testing purposes.
Fixes #
=> update(ci/registry): temporary disable cron job for registry ci

plugins/cloudtrail/pkg/cloudtrail/cloudtrail.go, plugins/cloudtrail/rules/aws_cloudtrail_rules.yaml, plugins/github/pkg/github/github.go, plugins/github/rules/github.yaml, plugins/k8saudit/pkg/k8saudit/k8saudit.go, plugins/k8saudit/rules/k8s_audit_rules.yaml
> /kind bug
> /kind design
/area plugins
> /area build
Bump the minor versions for the following plugins:
* k8saudit;
* cloudtrail;
* github.
The version bump is needed to release the new rulesfiles associated with the plugins since we updated the requirements of the rulesfiles in #210 
Fixes #
=> bump plugin versions

plugins/dummy/pkg/dummy/dummy.go
> /kind bug
> /kind design
/area build
Bump version of `dummy` plugin for testing purposes.
Fixes #
=> update(plugins/dummy): bump version to 8.0 for testing purpose

build/registry/go.mod, build/registry/go.sum
> /kind bug
/kind cleanup
> /kind design
/area build
This should be a no-op, since no relevant changes have been introduced in falcoctl that can have effect to the CI.
However, this PR can help to double-check if our expectation is correct. It will also make the version we use here close the the upcoming falcoctl release (that should happens in a few days).
/cc @jasondellaluce …
=> build(build/registry): bump falcoctl

release.md
> /kind bug
> /kind design
> /area build
Fixes #
=> docs(release.md): update the release process

build/registry/go.mod, build/registry/go.sum
> /kind bug
> /kind design
/area registry
> /area build
Bump `falcoctl` package to include fix: falcosecurity/falcoctl#230.
Fixes #
=> chore(registry/oci): bump falcoctl package to v0.3.0-rc2

plugins/okta/pkg/okta/okta.go
/kind feature
/area plugins
We would like to extract organization field even if not provided in the payload of each event
Fixes #
=> feature(plugins/okta): add okta.org as available field

plugins/okta/pkg/okta/okta.go
/kind feature
/area plugins
We are avoiding `api_token` and `organization` field from being required
Fixes #
=> feature(plugins/okta): make api token and organization field optional

.github/workflows/upload-oci-artifacts.yaml
> /kind bug
> /kind design
> /area build
Fetch git tags using the `checkout` action instead of running git on the runner.
Fixes #
=> update(oci/CI): fetch tags using checkout action

plugins/cloudtrail/pkg/cloudtrail/extract.go
/kind bug
/area plugins
Fixes #
=> fix(plugins/cloudtrail): set accountId to recipientAccountId if not present

plugins/okta/README.md, plugins/okta/pkg/okta/okta.go
/kind feature
/area plugins
Fixes #
=> feature(plugins/okta): add published timestamp field

plugins/okta/pkg/okta/okta.go
/kind bug
/area plugins
Fixes #
=> fix(plugins/okta): adjust mappings in actor.id and client.zone

plugins/okta/pkg/okta/okta.go
/kind bug
/area plugins
Fixes #
=> fix(plugins/okta): return nil if field not present

plugins/cloudtrail/pkg/cloudtrail/cloudtrail.go, plugins/cloudtrail/rules/aws_cloudtrail_rules.yaml, plugins/dummy/pkg/dummy/dummy.go, plugins/dummy_c/dummy.cpp, plugins/github/pkg/github/github.go, plugins/github/rules/github.yaml, plugins/json/pkg/json/json.go, plugins/k8saudit-eks/pkg/k8sauditeks/k8sauditeks.go, plugins/k8saudit/pkg/k8saudit/k8saudit.go, plugins/k8saudit/rules/k8s_audit_rules.yaml, plugins/okta/pkg/okta/okta.go, plugins/okta/rules/okta_rules.yaml
> /kind bug
> /kind design
/area plugins
> /area build
Bump the patch versions for the following plugins:
*  k8saudit;
*  cloudtrail;
* github;
* json;
* dummy;
* dummy_c;
* k8saudit-eks.
Bump the minor versions for the following plugins:
* okta.
The version bump is needed to release OCI artifacts for the plugins after the https://github.com/falcosecurity/plugins/pull/262 has been merged.
Fixes #
=> update(plugin-versions): bump plugins and rules versions

plugins/cloudtrail/pkg/cloudtrail/cloudtrail.go, plugins/cloudtrail/rules/aws_cloudtrail_rules.yaml, plugins/github/pkg/github/github.go, plugins/github/rules/github.yaml, plugins/k8saudit/pkg/k8saudit/k8saudit.go, plugins/k8saudit/rules/k8s_audit_rules.yaml
> /kind bug
> /kind design
> /area build
Fixes #
=> fix(plugins/k8saudit): fix dependencies in ruleset

.github/workflows/release.yml
/kind bug
/area build
This PR fixes the semver matching on tags.
`NONE`
`NONE`
=> fix(ci): fixed semver matching release gha.

plugins/dummy/pkg/dummy/dummy.go
/kind feature
/area plugins
This PR is needed to test the [`release`](https://github.com/falcosecurity/plugins/blob/master/.github/workflows/release.yml) pipeline.
`NONE`
A new tag of `dummy` plugin is required to trigger the GHA.
=> chore(plugins/dummy/pkg/dummy/dummy.go): bump dummy plugin version to test release gha.

.github/workflows/push_master.yml
/kind bug
/area build
This PR fixes the branch name matched by the [`push_master`](https://github.com/falcosecurity/plugins/blob/master/.github/workflows/push_master.yml) gha.
`NONE`
`NONE`
=> fix(ci): fixed branch name push_master pipeline.

.github/workflows/push_master.yml, .github/workflows/release.yml
/kind bug
/area build
This PR adds permissions to `push_master` and `release` GHA to allow authentication on S3. 
It also fixes volume the volume mounts in arm64 builds.
`NONE`
`NONE`
=> fix(ci): added permissions for S3 upload and volume mount on qemu.

release.md
This PR updates the documentation about the release process.
`NONE`
`NONE`
=> chore(release.md): updated release process CI documentation.

plugins/github/README.md
=> chore(docs): more clear params

plugins/dummy_c/Makefile, plugins/dummy_c/api.cpp, plugins/dummy_c/dummy.cpp, plugins/dummy_c/dummy.h
> /kind bug
/kind cleanup
> /kind design
/area plugins
> /area build
The dummy_c plugin was written with the old apis.
Fixes #
=> update(dummy_c): rewrite with the new api

.github/workflows/push_master.yml, .github/workflows/release.yml
=> fix(ci): fix arm64 master and release ci push step

.github/workflows/ci.yaml, .github/workflows/master.yaml, .github/workflows/release.yml, .github/workflows/reusable_build_packages.yaml, .github/workflows/reusable_publish_packages.yaml
/kind cleanup
/area build
Fixes #
=> new(ci): reusable workflows

.gitignore, plugins/cloudtrail/go.mod, plugins/cloudtrail/go.sum, plugins/json/go.mod, plugins/json/go.sum, plugins/k8saudit/go.mod, plugins/k8saudit/go.sum
/kind bug
/area plugins
This is a follow-up of after the fixes of https://github.com/falcosecurity/plugin-sdk-go/pull/75.
=> update(plugins): bump sdk go to latest dev version

registry.yaml
> /kind bug
> /kind design
/kind feature
/area plugins
> /area build
This PR adds a plugin for the dnscollector project (https://github.com/dmachard/go-dnscollector)
Fixes #
=> add dnscollector plugin

registry.yaml
> /kind bug
> /kind design
/area registry
> /area build
add keywords for k8saudit-eks plugin
Fixes #
=> add keywords for k8saudit-plugin

plugins/cloudtrail/pkg/cloudtrail/cloudtrail.go, plugins/cloudtrail/rules/aws_cloudtrail_rules.yaml, plugins/dummy/pkg/dummy/dummy.go, plugins/github/pkg/github/github.go, plugins/github/rules/github.yaml, plugins/json/pkg/json/json.go, plugins/k8saudit-eks/pkg/k8sauditeks/k8sauditeks.go, plugins/k8saudit/pkg/k8saudit/k8saudit.go, plugins/k8saudit/rules/k8s_audit_rules.yaml, plugins/okta/pkg/okta/okta.go, plugins/okta/rules/okta_rules.yaml
/kind cleanup
/area plugins
Bumping the versions of all plugins that will be released alongside the new Falco 0.35.
=> update(plugins): bump to-be-released plugin versions

.github/workflows/release.yml
=> fix(ci/release.yaml): fix release version check on publish

.github/workflows/release.yml
/kind bug
/kind cleanup
/area build
=> update(ci/release.yaml): avoid cancelling concurrent release jobs

registry.yaml
> /kind bug
> /kind design
/kind feature
/area plugins
> /area build
Add a new plugin to the registry
https://github.com/nabokihms/syslogsrv-falco-plugin
Fixes #
=> Add syslogsrv plugin

plugins/gcpaudit/Makefile, plugins/gcpaudit/README.md, plugins/gcpaudit/pkg/gcpaudit/config.go, plugins/gcpaudit/pkg/gcpaudit/extract.go, plugins/gcpaudit/pkg/gcpaudit/gcpaudit.go, plugins/gcpaudit/pkg/gcpaudit/init.go, plugins/gcpaudit/pkg/gcpaudit/source.go
/kind bug
/kind cleanup
/area plugins
Minor improvements and refactors to the gcpaudit plugin before proceeding with a first release.
=> refactor(plugins/gcpaudit): improvements for first release

.github/workflows/reusable_validate_plugins.yaml
/kind bug
/area build
Since in the CI during validation we _may_ build some plugins on the fly, we need to build inside the same container used for building the dev plugin artifacts so that the glibc requirements are met.
=> fix(ci): validate in container to satisfy glibc requirements

.github/workflows/reusable_validate_plugins.yaml, plugins/gcpaudit/rules/gcp_auditlog_rules.yaml
=> fix(ci): solve validation workflow issues

plugins/dummy/dummy_rules.yaml
/kind feature
/area plugins
This rule can be useful for testing
=> new(dummy): add an example rule for the dummy plugin

plugins/gcpaudit/go.mod
/kind bug
> /kind design
/area plugins
> /area build
Fixes #
=> fix(plugins/gcpaudit) correct module name

.github/workflows/upload-oci-artifacts.yaml
/kind bug
/area build
The workflow did not have explicit permissions on both jobs. These permissions may now be required.
Fixes #
=> fix(build): add permissions for push step

plugins/gcpaudit/pkg/gcpaudit/gcpaudit.go
/kind feature
/area plugins
As per title.
Fixes #
=> update(gcpaudit): bump version to 0.1.3

build/registry/pkg/oci/oci.go
/kind bug
/area build
We have plugin signatures now, so we need this.
Fixes #
=> fix(build): skip non-semver tags during oci publishing

plugins/gcpaudit/pkg/gcpaudit/gcpaudit.go
/kind cleanup
/area plugins
Bumping gcpaudit to 0.2.0 before tagging it, to include the recent bug fixes and new fields.
=> update(plugins/gcpaudit): bump version to 0.2.0

plugins/gcpaudit/pkg/gcpaudit/extract.go
Signed-off-by: Lorenzo Merici <lorenzo.merici@sysdig.com>
> /kind bug
> /kind design
> /area build
Fixes #
=> fix(plugins/gcp): add missing string conversions

plugins/gcpaudit/pkg/gcpaudit/gcpaudit.go
> /kind bug
> /kind design
> /area build
Fixes #
=> update(gcpaudit): bump version to 0.2.1

plugins/cloudtrail/pkg/cloudtrail/cloudtrail.go, plugins/dummy/pkg/dummy/dummy.go, plugins/github/pkg/github/github.go, plugins/json/pkg/json/json.go, plugins/k8saudit-eks/pkg/k8sauditeks/k8sauditeks.go, plugins/k8saudit/pkg/k8saudit/k8saudit.go, plugins/okta/pkg/okta/okta.go
/kind cleanup
/area plugins
Bump plugin versions for the upcoming Falco 0.36.0 release.
Fixes #
=> update(plugins): bump to-be-released plugin versions.

plugins/gcpaudit/pkg/gcpaudit/extract.go
Signed-off-by: Lorenzo Merici <lorenzo.merici@sysdig.com>
> /kind bug
> /kind design
> /area build
Fixes #
=> fix(plugins/gcp): conversion error for empty zone

plugins/gcpaudit/pkg/gcpaudit/gcpaudit.go
> /kind bug
> /kind design
> /area build
Fixes #
=> update(gcpaudit): bump version to 0.2.2

plugins/k8saudit-eks/README.md
> /kind bug
> /kind design
/area plugins
> /area build
Explain more how to use the plugin in an EKS env
Fixes #
=> update k8saudit-eks readme to explain how to deploy in EKS

plugins/github/pkg/github/server.go
/kind bug
/area plugins
The PR is related to a bug in the GitHub plugin that causes it to crash whenever a new branch is created or deleted. This is because GitHub WebHook sends a push event before create or delete events on creation or deletion of a branch. In that case, the plugin uses null commit ID for comparison, which returns status 404, crashing the plugin.
The PR adds a check to ensure that the before or after commit IDs are not null. This indicates that a branch was not created or deleted, and the plugin can then proceed with scanning the commit.
More on the issue here: https://kubernetes.slack.com/archives/CMWH3EH32/p1690024814329709?thread_ts=1678097469.6 …
=> fix(plugins/github): add a check that before and after commit IDs aren't null

README.md, build/registry/pkg/registry/types.go, build/registry/pkg/registry/validate.go, docs/plugin-ids.md, registry.yaml
/kind design
/area registry
/area build
This PR aims to introduce precise guidelines for plugin ID usage. In particular, it mandates specific rules for reserved ID blocks. Also, it handles the `0` value exceptional cases, which libs may use in the future for particular purposes.
Fixes #
=> Plugin ID blocks

plugins/cloudtrail/pkg/cloudtrail/extract.go
/kind bug
/area plugins
Fixes #
=> fix(plugins/cloudtrail): remove wrong return statement when extracting recipientAccountId

plugins/cloudtrail/pkg/cloudtrail/cloudtrail.go
/kind cleanup
/area plugins
As per title.
Fixes #
=> chore(cloudtrail): bump version to 0.9.1

.github/workflows/reusable_build_packages.yaml
=> new(ci): use actuated arm nodes.

.github/workflows/ci.yaml, .github/workflows/master.yaml, .github/workflows/release.yml
/kind feature
/area build
This PR bumps Falco and Falcoctl to latest versions
=> chore(CI): bump Falco and Falcoctl to latest versions

registry.yaml
/area registry
This PR adds `k8smeta` plugin to the registry
=> update(registry): add `k8smeta` plugin to the registry

plugins/k8smeta/src/shared_with_tests_consts.h
/kind feature
/area plugins
change plugin version to `0.1.0-alpha`
=> update(k8smeta): change plugin version to `0.1.0-alpha`

registry.yaml
> /kind bug
> /kind design
/kind feature
/area plugins
> /area build
Provides ingestion of Salesforce Real-Time Event Monitoring Objects into Falco (via GRPC) to provide basic runtime threat detection and auditing logging for Salesforce 
=> salesforce plugin

plugins/json/pkg/json/json.go, plugins/json/pkg/json/json_test.go
Signed-off-by: lorenzo-merici <lorenzo.merici@sysdig.com>
/kind bug
> /kind design
/area plugins
> /area build
Fixes #
=> fix(plugins/json): add check for empty ArgKey

plugins/json/pkg/json/json.go
Signed-off-by: lorenzo-merici <lorenzo.merici@sysdig.com>
> /kind bug
> /kind design
> /area build
Fixes #
=> update(json): bump version to 0.7.2

plugins/dummy/pkg/dummy/dummy.go
/kind feature
/area plugins
As per title
Fixes #
=> chore(plugins/dummy): bump dummy to 0.10.0-rc1

build/registry/pkg/oci/oci.go
/kind bug
/area build
As per title. I previously forgot the arg...
Fixes #
=> fix(ci): add debug line for not semver

build/registry/pkg/common/consts.go, build/registry/pkg/oci/requirements.go
/kind cleanup
/area build
"Wax on, wax off". As per previous description: https://github.com/falcosecurity/plugins/pull/400
Fixes #
=> update(build): add back PR #373

plugins/k8smeta/cmake/modules/libs.cmake, plugins/k8smeta/src/shared_with_tests_consts.h
/kind feature
/area plugins
This PR bumps `k8smeta` plugin to 0.1.0
=> Bump k8smeta plugin to 0.1.0

registry.yaml
> /kind bug
/kind cleanup
> /kind design
/area registry
> /area build
Update the `registry.yaml` file to trigger the CI.
Fixes #
=> update(registry.yaml): update the copyright

plugins/cloudtrail/pkg/cloudtrail/extract.go
> /kind bug
> /kind design
/kind feature
/area plugins
> /area build
Fixes #
=> feat(cloudtrail): support s3 events

plugins/cloudtrail/pkg/cloudtrail/cloudtrail.go, plugins/cloudtrail/rules/aws_cloudtrail_rules.yaml
> /kind bug
> /kind design
> /area build
Fixes #
=> feat(cloudtrail): bump cloudtrail plugin version to 0.11.0

plugins/cloudtrail/pkg/cloudtrail/extract.go
> /kind bug
> /kind design
> /area build
Fixes #
=> fix: s3.cnt.other condition

plugins/k8smeta/README.md
/area plugins
> /area build
This PR  updates the k8smeta doc
Fixes #420
=> docs(k8smeta): update k8smeta doc

plugins/cloudtrail/pkg/cloudtrail/source.go
/kind feature
/area plugins
Add support for organization trail path as documented at https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-find-log-files.html
=> feat(cloudtrail): Support for organization trails

.github/workflows/ci.yaml, .github/workflows/master.yaml, .github/workflows/release.yml
> /kind bug
/kind cleanup
> /kind design
/area build
It upgrades the versions of falco and falcoctl used in the CI. 
#424 
Fixes #
=> update the versions of falco and falcoctl in the CI

plugins/okta/OWNERS
> /kind bug
> /kind design
/area plugins
> /area build
I'm the developer of this plugin, seems fair to me to be allowed to approve the PR from the community, especially because I'm still continue to develop/answer the issue/review the PR.
Fixes #
=> vote: add Issif as owner of the okta plugin for the PR approvals

plugins/cloudtrail/pkg/cloudtrail/source.go
/kind cleanup
/area plugins
To speed up the process of getting all the keys, divide the inputParams array into chunks and get the keys for each item in the chunk concurrently.
This should be my last commit for the time being. This means that version 0.12 can be released (after testing by third parties).
=> refactor(cloudtrail): Get S3 keys concurrently

plugins/okta/CHANGELOG.md, plugins/okta/README.md, plugins/okta/pkg/okta/okta.go, plugins/okta/rules/okta_rules.yaml
/kind bug
/area plugins
We need it to capture the application alternate ID (which is more explicit than application name) and populate that information in alerts to make them more actionable.
Fixes #427 
This is my first PR for this project don't hesitate to provide feedback on "what could have been better". Thanks.
/cc @Issif
=> Fix application name extraction issue

.github/workflows/master.yaml, .github/workflows/release.yml, .github/workflows/reusable-publish-oci-artifacts.yaml, build/registry/cmd/registry/registry.go, build/registry/pkg/common/extract.go, build/registry/pkg/oci/const.go, build/registry/pkg/oci/oci.go
> /kind bug
> /kind design
> /area build
This PR enables the publishing of OCI artifacts for the master and release workflows without the need of manual intervention.
Fixes #
=> update(CI): publish oci artifacts for master and release workflows

.github/workflows/master.yaml, .github/workflows/release.yml, .github/workflows/reusable-publish-oci-artifacts.yaml
> /kind bug
> /kind design
> /area build
Fixes #
=> fix(CI): add suffix input to oci workflow

.github/workflows/reusable-publish-oci-artifacts.yaml
> /kind bug
> /kind design
> /area build
Fixes #
=> fix(CI): fix command in oci artifacts

.github/workflows/reusable-publish-oci-artifacts.yaml
/kind cleanup
/area build
As per title
Fixes #
=> update(ci): update cosign version

.github/workflows/release.yml
> /kind bug
> /kind design
> /area build
Fixes #
=> fix(oci): fix dependencies for publish-oci-artifacts workflow

.github/workflows/reusable-publish-oci-artifacts.yaml
> /kind bug
> /kind design
> /area build
Fixes #
=> fix(ci): set empty string as a flag when not specified by the ci

plugins/github/pkg/github/github.go
> /kind bug
> /kind design
/area plugins
> /area build
Fixes #
=> chore(github): bump version to 0.7.2

plugins/dummy/pkg/dummy/dummy.go
/kind cleanup
/area plugins
As per title
Fixes #
=> chore(plugins): bump dummy plugin version

plugins/k8saudit-gke/README.md
> /kind bug
> /kind design
/area plugins
> /area build
Explaining the Pub/Sub setup alternatives: Pub/Sub topic in same project as GKE cluster(s) or a shared Pub/Sub topic used as log sink by every project with GKE cluster(s).
Fixes #441 
=> docs(k8saudit-gke): Explain Pub/Sub setup alternatives

plugins/k8saudit-gke/README.md
> /kind bug
> /kind design
/area plugins
> /area build
Adding some notes on processing high audit log volumes with k8saudit-gke.
Fixes #
=> docs(k8saudit-gke): describe scaling options for high audit log volumes

release.md
> /kind bug
> /kind design
> /area build
update(docs): update release docs
see #440 
Fixes #
=> update(docs): update release docs

build/registry/pkg/oci/configLayer.go, build/registry/pkg/oci/oci.go, build/registry/pkg/oci/requirements.go
> /kind bug
> /kind design
> /area build
fix(ci): support release of plugins with same prefix
Cases such k8saudit and k8saudit-gke need special handling when pushing artifacts.
Fixes #
=> fix(ci): support release of plugins with same prefix

registry.yaml
> /kind bug
> /kind design
/kind feature
/area registry
> /area build
This PR reserves plugin ID 514 for the journald plugin: https://github.com/gnosek/falco-journald-plugin
Fixes #
514 is the syslog port, it felt appropriate :)
=> update(registry.yaml): register journald plugin

plugins/dummy/pkg/dummy/dummy.go
> /kind bug
> /kind design
/area plugins
> /area build
update(dummy): bump version for ci testing purpose
Fixes #
=> update(dummy): bump version for ci testing purpose

.github/workflows/release.yml
> /kind bug
> /kind design
> /area build
fix(CI): extract info from plugin tag
Fixes #
=> fix(CI): extract info from plugin tag

plugins/k8saudit/pkg/k8saudit/k8saudit.go
/kind bug
> /kind design
/area plugins
> /area build
Release the updated k8saudit rules, which are required by the k8saudit-gke rules
Fixes #
=> chore(k8saudit): bump version to 0.8.0 to release rule changes

plugins/gcpaudit/pkg/gcpaudit/gcpaudit.go
> /kind bug
> /kind design
/area plugins
> /area build
Bump version.
Fixes #
=> update(gcpaudit): bump version to 0.3.2

plugins/github/pkg/github/github.go
**What type of PR is this?*
> /kind bug
> /kind design
/area plugins
> /area build
Bump version
Fixes #
=> update(github): bump version to 0.7.3

.github/get-latest-plugin-version.sh
/kind bug
> /kind design
/area build
fix(ci): correctly retrieve plugin version from tag
Fixes #
=> fix(ci): correctly retrieve plugin version from tag

Makefile
/kind bug
> /kind design
/area build
k8saudit-gke ships a rulesfiles that overrides the k8saudit rules. To make the CI happy we have a symlink of the original k8saudit rules in k8saudit-gke/rules directory. This commit filters out the symlinks when releasing the rulesfiles.
Fixes #
=> fix(release/rules): ignore symlinks when releasing rulesfiles

.github/workflows/reusable_suggest_rules_version.yaml
> /kind bug
> /kind design
> /area build
fix(ci): correctly fetch repository head
Fixes #
=> fix(ci): correctly fetch repository head

plugins/k8saudit-gke/CHANGELOG.md, plugins/k8saudit-gke/pkg/k8sauditgke/k8sauditgke.go
/kind bug
> /kind design
/area plugins
> /area build
Bump k8saudit-gke version to 0.1.1 to trigger the release of a new rules artifact including fix https://github.com/falcosecurity/plugins/commit/e45070ffde9ed6d69c07f25836076ae22aa3ab71
Fixes #
=> Bump k8saudit-gke to 0.1.1 to release rules

plugins/k8saudit-gke/pkg/k8sauditgke/convert.go, plugins/k8saudit-gke/pkg/k8sauditgke/source.go
/kind feature
/area plugins
For the project I have we are ingesting gke events in other way and we would like to leverage already existing OSS code for converting gke events to `k8s_audit` ones, due to maintainability reasons.
Fixes #
=> plugins(k8saudit-gke): export ConvertLogEntry method

plugins/kafka/pkg/kafka/kafka.go
> /kind bug
> /kind design
> /area build
Fixes #
=> docs(plugins/kafka): update description and contact

build/registry/cmd/validateRegistry/validateRegistryFile.go, build/registry/pkg/oci/const.go, build/registry/pkg/oci/oci.go
> /kind bug
> /kind design
/area plugins
/area registry
> /area build
fix(CI): use the repo URL as source of truth for plugin's owner
Fixes #
=> fix(CI): use the repo URL as source of truth for plugin's owner

plugins/k8saudit/pkg/k8saudit/extract.go, plugins/k8saudit/pkg/k8saudit/fields.go
/kind feature
/area plugins
Fixes #
=> feat(plugins/k8saudit): extract cluster name

plugins/k8saudit/pkg/k8saudit/extract.go, plugins/k8saudit/pkg/k8saudit/fields.go
/kind feature
/area plugins
Fixes #
=> feat(plugins/k8saudit): extract pod name

.github/workflows/reusable_build_packages.yaml
/kind bug
/area build
As per title. This increases library compatibility.
Fixes #
=> fix(ci): build plugins on debian bullseye

plugins/k8saudit/pkg/k8saudit/k8saudit.go
/kind cleanup
/area plugins
Preparing for release
Fixes #
=> chore(plugin/cloudtrail): bump cloudtrail version to 0.10.0-rc1

plugins/k8saudit-eks/go.mod, plugins/k8saudit-eks/go.sum, plugins/k8saudit-eks/pkg/k8sauditeks/k8sauditeks.go, plugins/k8saudit-gke/go.mod, plugins/k8saudit-gke/go.sum, plugins/k8saudit-gke/pkg/k8sauditgke/k8sauditgke.go
/kind cleanup
/area plugins
As per title. This is necessary to make sure they use the latest version.
Fixes #
=> chore(plugins): update k8saudit eks and gke with k8saudit 0.10.0

.github/workflows/reusable_build_packages.yaml
/kind cleanup
/area build
We may forget why we are actually using bullseye. This reminds us.
Fixes #
=> chore(build): add comment about upgrading debian version

.github/workflows/reusable-publish-oci-artifacts.yaml
/kind bug
/area build
As per title
Fixes #
=> chore(ci): update cosign-installer to v3.5.0

plugins/cloudtrail/CHANGELOG.md, plugins/dummy/CHANGELOG.md, plugins/dummy_c/CHANGELOG.md, plugins/gcpaudit/CHANGELOG.md, plugins/github/CHANGELOG.md, plugins/json/CHANGELOG.md, plugins/k8saudit-eks/CHANGELOG.md, plugins/k8saudit-gke/CHANGELOG.md, plugins/k8saudit/CHANGELOG.md, plugins/k8smeta/CHANGELOG.md, plugins/kafka/CHANGELOG.md, plugins/okta/CHANGELOG.md
> /kind bug
> /kind design
/area plugins
> /area build
Fixes #
=> docs: bulk update for changelogs

plugins/k8saudit-eks/CHANGELOG.md, plugins/k8saudit-gke/CHANGELOG.md
> /kind bug
> /kind design
/area plugins
> /area build
Fixes #
=> docs: k8saudit-{eks,gke} changelogs

registry.yaml
> /kind bug
> /kind design
/kind feature
/area plugins
> /area build
Fixes #
=> Falco plugin for GitLab

plugins/k8smeta/src/plugin.cpp
> /kind bug
> /kind design
/area plugins
> /area build
Fixes #
=> chore(k8smeta): adjust logging level

plugins/k8smeta/src/shared_with_tests_consts.h
> /kind bug
> /kind design
/area plugins
> /area build
Fixes #
=> chore(k8smeta): bump k8smeta version to 0.2.1

plugins/k8saudit/pkg/k8saudit/k8saudit.go
Since https://github.com/falcosecurity/plugins/pull/528 is introducing a backward incompatible change within the ruleset
> /kind bug
> /kind design
/kind feature
/area plugins
> /area build
Fixes #
I will release the plugins afterward.
=> update(k8saudit): bump to v0.11

.github/workflows/reusable_build_packages.yaml
> /kind bug
> /kind design
/area build
See https://github.com/falcosecurity/plugins/actions/runs/11915482691/job/33205849937
Fixes #
=> fix(ci): add libelf-dev system dep for building packages

plugins/k8smeta/src/plugin.cpp, plugins/k8smeta/src/plugin.h
/kind feature
/area plugins
improve k8smeta logging
=> update(k8smeta): improve k8smeta logging

plugins/gcpaudit/CHANGELOG.md, plugins/gcpaudit/pkg/gcpaudit/gcpaudit.go, plugins/github/CHANGELOG.md, plugins/k8saudit-gke/CHANGELOG.md, plugins/k8saudit-gke/pkg/k8sauditgke/k8sauditgke.go, plugins/k8saudit/CHANGELOG.md, plugins/k8smeta/CHANGELOG.md, plugins/kafka/CHANGELOG.md, plugins/kafka/pkg/kafka/kafka.go
> /kind bug
/kind cleanup
> /kind design
/area plugins
> /area build
Fixes #
=> prepare plugin releases (for deps upgrade)

.github/workflows/reusable_build_packages.yaml
/kind cleanup
/area build
As per title
Fixes #
=> update(build): upgrade golang to 1.23

.github/workflows/reusable_build_packages.yaml
=> chore(ci): switch to use github provided arm runner.

plugins/k8saudit-aks/go.mod, plugins/k8saudit-aks/go.sum, plugins/k8saudit-eks/go.mod, plugins/k8saudit-eks/go.sum, plugins/k8saudit-gke/go.mod, plugins/k8saudit-gke/go.sum, plugins/k8saudit-ovh/go.mod, plugins/k8saudit-ovh/go.sum
> /kind bug
/kind cleanup
> /kind design
/area plugins
> /area build
Fixes #
=> update(plugins/k8saudit-*): bump k8saudit plugin dep to v0.12

registry.yaml
> /kind bug
> /kind design
/area registry
> /area build
See https://github.com/falcosecurity/test-infra/blob/master/config/jobs/build-plugins/build-plugins.yaml 
We need the job to run to update the falcoctl index.
Fixes #
=> chore(registry.yaml): update registry to trigger the CI

.github/dependabot.yml
/kind bug
> /kind design
> /area build
Fixes #
=> fix(.github): add go mod tidy for dependabot.yml

.github/dependabot.yml
/kind bug
> /kind design
> /area build
Fixes #
=> revert: fix(.github): add go mod tidy for dependabot.yml

registry.yaml
> /kind bug
/kind cleanup
> /kind design
/area registry
> /area build
This is mainly required to test the CI.
Fixes #
=> chore(registry.yaml): small change to trigger the CI

README.md, docs/registering-a-plugin.md
> /kind bug
/kind cleanup
> /kind design
> /area build
Fixes #
=> docs: update readme

registry.yaml
=> cleanup(registry): drop newline.

plugins/container/CMakeLists.txt, plugins/container/src/macros.h.in, plugins/container/src/plugin.h
/kind cleanup
/area plugins
Prepare container plugin for 0.2.0 tag.
Fixes #
=> chore(plugins/container): bump container plugin to 0.2.0.

plugins/container/src/caps/extract/extract.cpp, plugins/container/src/caps/listening/listening.cpp, plugins/container/src/caps/parse/parse.cpp, plugins/container/src/plugin.cpp
/kind cleanup
/area plugins
Fixes #
=> chore(plugins/container): broaden exceptions management.

plugins/k8smeta/src/plugin.cpp
/kind cleanup
/area plugins
Fixes #
=> chore(plugins/k8smeta): broaden exception mgmt.

plugins/github/pkg/github/extract.go, plugins/github/pkg/github/github.go
> /kind bug
> /kind design
/kind feature
/area plugins
> /area build
Fixes #
For reference: https://docs.github.com/en/webhooks/webhook-events-and-payloads#push
=> new(gitub): add fileds for `added` and `removed` files

plugins/cloudtrail/pkg/cloudtrail/cloudtrail.go
> /kind bug
> /kind design
/kind feature
/area plugins
> /area build
Fixes #
=> update(cloudtrail): bump to v0.13.0

plugins/krsi/krsi/src/lib.rs
/kind bug
> /kind design
/area plugins
> /area build
This PR fixes the KRSI plugin version.
Fixes #
=> fix(plugins/krsi): fix plugin version

registry.yaml
> /kind bug
> /kind design
/area registry
> /area build
Triggering CI.
Fixes #
=> ci: trigger CI

plugins/dummy_rs/Cargo.lock
/kind bug
> /kind design
/area plugins
> /area build
This PR realigns `dummy_rs` plugin's `Cargo.lock` file. 
Fixes #
=> fix(plugins/dummy_rs): sync `Cargo.lock`

.pre-commit-config.yaml, README.md, plugins/dummy_rs/rustfmt.toml, plugins/dummy_rs/src/libdummy_rs.rs, plugins/krsi/README.md, plugins/krsi/rustfmt.toml, tools/local_hooks/dco-pre-commit-msg.sh
> /kind bug
/kind cleanup
> /kind design
/area plugins
> /area build
This PR enforces global coding style and policies by leveraging the `pre-commit` framework. It moves the `krsi` plugin's specific `pre-commit` configuration to the root of the project, tweaking its `rustfmt.toml` file to enforce the `rustfmt` tool's edition on a plugin-basis instead of enforcing it globally in the corresponding `pre-commit` hook. It updates the `krsi` plugin's `README.md` to point to a new project's …
=> chore: add pre-commit hooks for enforcing coding style and policies

.github/dependabot.yml
> /kind bug
> /kind design
/kind feature
/area plugins
/area build
This PR adds the configuration for `dependabot` to handle `cargo` dependencies upgrades. "Minor" and "patch" dependencies upgrades are coalesced in a single PR, while specific PRs are created for each single "major" dependency upgrade.
Fixes #
=> ci: add config for dependabot to handle `cargo` dependencies

plugins/krsi/OWNERS
> /kind bug
> /kind design
/area plugins
> /area build
Hi folks!
As I have worked on the eBPF-side implementation of the `krsi` plugin, encouraged by @leogr  in https://github.com/falcosecurity/plugins/pull/727#issuecomment-2838185646 , I would like to propose myself as maintainer of the `krsi` plugin.
Fixes #
=> vote: docs(plugins/krsi): add `ekoops` as maintainer

plugins/krsi/krsi-common/src/lib.rs, plugins/krsi/krsi/src/krsi_event.rs, plugins/krsi/krsi/src/lib.rs
/kind bug
/kind cleanup
> /kind design
/area plugins
> /area build
This PR cleans the userspace implementation of the the `krsi` plugin, by replacing any unsafe code with a safer and more structured approach.
Special thanks to @gnosek for its contribution and knowledge share!
Fixes #
=> fix(plugins/krsi): use safe ring buffer events parsing logic

plugins/krsi/krsi-ebpf/src/auxbuf.rs, plugins/krsi/krsi-ebpf/src/main.rs, plugins/krsi/krsi-ebpf/src/operations/bind.rs, plugins/krsi/krsi-ebpf/src/operations/connect.rs, plugins/krsi/krsi-ebpf/src/operations/linkat.rs, plugins/krsi/krsi-ebpf/src/operations/mkdirat.rs, plugins/krsi/krsi-ebpf/src/operations/open.rs, plugins/krsi/krsi-ebpf/src/operations/renameat.rs, plugins/krsi/krsi-ebpf/src/operations/socket.rs, plugins/krsi/krsi-ebpf/src/operations/symlinkat.rs, plugins/krsi/krsi-ebpf/src/operations/unlinkat.rs, plugins/krsi/krsi-ebpf/src/shared_state.rs, plugins/krsi/krsi/src/ebpf.rs
> /kind bug
/kind cleanup
> /kind design
/area plugins
> /area build
This replaces the "auxiliary map" name with "auxiliary buffer", as this name fits more its purpose.
Fixes #
=> refactor(plugins/krsi/krsi-ebpf): rename `auxmap` to `auxbuf`

plugins/krsi/krsi-ebpf/src/auxbuf.rs
> /kind bug
/kind cleanup
> /kind design
/area plugins
> /area build
This PR changes the internal auxbuf methods' naming convention from using `push*` to `write*`.
Fixes #
=> refactor(plugins/krsi/krsi-ebpf): change auxbuf internal naming conv

plugins/krsi/krsi-ebpf/src/auxbuf.rs, plugins/krsi/krsi-ebpf/src/operations/bind.rs, plugins/krsi/krsi-ebpf/src/operations/connect.rs, plugins/krsi/krsi-ebpf/src/operations/linkat.rs, plugins/krsi/krsi-ebpf/src/operations/mkdirat.rs, plugins/krsi/krsi-ebpf/src/operations/open.rs, plugins/krsi/krsi-ebpf/src/operations/renameat.rs, plugins/krsi/krsi-ebpf/src/operations/socket.rs, plugins/krsi/krsi-ebpf/src/operations/symlinkat.rs, plugins/krsi/krsi-ebpf/src/operations/unlinkat.rs
> /kind bug
/kind cleanup
/kind design
/area plugins
> /area build
This PR introduces `auxbuf` `Writer` abstraction to split data container from business logic writing into them.
Fixes #
=> refactor(plugins/krsi/krsi-ebpf): introduce auxbuf writer abstraction

plugins/k8saudit-gke/pkg/k8sauditgke/k8sauditgke.go
> /kind bug
/kind cleanup
> /kind design
/area plugins
> /area build
Since v0.5.0 has not been released yet.
Fixes #
=> revert: update(plugins/k8saudit-gke): bump to v0.6.0

plugins/krsi/krsi-ebpf-core/src/lib.rs, plugins/krsi/krsi-ebpf/src/auxbuf.rs, plugins/krsi/krsi-ebpf/src/operations/bind.rs, plugins/krsi/krsi-ebpf/src/operations/connect.rs, plugins/krsi/krsi-ebpf/src/operations/linkat.rs, plugins/krsi/krsi-ebpf/src/operations/mkdirat.rs, plugins/krsi/krsi-ebpf/src/operations/open.rs, plugins/krsi/krsi-ebpf/src/operations/renameat.rs, plugins/krsi/krsi-ebpf/src/operations/socket.rs, plugins/krsi/krsi-ebpf/src/operations/symlinkat.rs, plugins/krsi/krsi-ebpf/src/operations/unlinkat.rs, plugins/krsi/krsi-ebpf/src/operations/writer_helpers.rs
/kind bug
/kind cleanup
> /kind design
/area plugins
> /area build
This PR properly handles `auxbuf` writing errors.
Fixes #
=> fix(plugins/krsi): properly handle `auxbuf` writing errors

plugins/krsi/krsi/src/lib.rs
> /kind bug
/kind cleanup
> /kind design
/area plugins
> /area build
This PR fixes the extracted field description formatting.
Fixes #
=> refactor(plugins/krsi/krsi): fix extracted field desc formatting

plugins/container/CMakeLists.txt
/kind cleanup
/area plugins
As per title
Fixes #
=> chore(plugins/container): bump version to 0.2.4

plugins/anomalydetection/CHANGELOG.md, plugins/cloudtrail/CHANGELOG.md, plugins/collector/CHANGELOG.md, plugins/container/CHANGELOG.md, plugins/dummy/CHANGELOG.md, plugins/dummy_c/CHANGELOG.md, plugins/gcpaudit/CHANGELOG.md, plugins/github/CHANGELOG.md, plugins/json/CHANGELOG.md, plugins/k8saudit-aks/CHANGELOG.md, plugins/k8saudit-eks/CHANGELOG.md, plugins/k8saudit-gke/CHANGELOG.md, plugins/k8saudit-ovh/CHANGELOG.md, plugins/k8saudit/CHANGELOG.md, plugins/k8smeta/CHANGELOG.md, plugins/kafka/CHANGELOG.md, plugins/krsi/CHANGELOG.md, plugins/okta/CHANGELOG.md
> /kind bug
> /kind design
/area plugins
> /area build
This PR updates plugins changelogs.
Fixes #
=> docs(plugins): update plugins changelogs

plugins/container/go-worker/pkg/container/fetcher.go, plugins/container/go-worker/pkg/container/fetcher_test.go, plugins/container/go-worker/worker_api.go, plugins/container/src/plugin.cpp
/kind cleanup
/area plugins
Fixes #
=> chore(plugins/container): let async_ctx own the fetcher channel.

OWNERS, plugins/krsi/OWNERS
> /kind bug
> /kind design
/area plugins
> /area build
Hi folks!
As I have worked on the eBPF-side implementation of the krsi plugin, and investigated on some container plugin issues, I would like to propose myself as maintainer of this repo.
Fixes #
=> vote: docs: add `ekoops` as maintainer

registry.yaml
/kind feature
/area registry
Introduced a new Falco plugin with source and extractor capabilities for AWS ELB Access Logs events
Fixes #
=> feat: Add plugin for AWS ELB Access Log

plugins/container/CMakeLists.txt
/kind bug
> /kind design
/area plugins
> /area build
Fixes #
=> update(plugins/container): bump to v0.3.3

plugins/container/CHANGELOG.md, plugins/dummy_rs/CHANGELOG.md, plugins/k8smeta/CHANGELOG.md
/area plugins
Also, added new dummy_rs changelog.
Fixes #
=> update(plugins): updated CHANGELOGS.

plugins/container/CMakeLists.txt, plugins/container/src/container_info_json.cpp
/kind bug
/area plugins
Fix flat container info json.
e.g. I got the following at container_removed async event:
```json
{"Mounts":[],"User":"","cni_json":"","container":null,"cpu_period":100000,"cpu_quota":0,"cpu_shares":1024,"cpuset_cpu_count":0,"created_time":1754348534,"env":[],"full_id":"9ad51caebe3ace3a44520b2df0c0e5fd00c2c3f90db98fb94312f631514a4010","host_ipc":false,"host_network":false,"host_pid":false,"id":"9ad51caebe3a","image":"busybox:stable","imagedigest":"sha256:c3839dd800b9eb7603340509769c43e146a74c63dca3045a8e7dc8ee07e53966","imageid":"ba5dc23f65d4cc4a4535bce55cf9e63b068eb02946e3422d3587e8ce803b6aab","imagerepo":"busybox","imagetag":"stable","ip":"" …
```
=> fix(plugins/container): container_info to_json

plugins/container/go-worker/main_exe.go, plugins/container/go-worker/pkg/container/cri_test.go, plugins/container/go-worker/pkg/container/docker_test.go
/kind feature
/area plugins
Fixes #
=> new(plugins/container): add pprof to go-worker demo executable.

plugins/cloudtrail/README.md, plugins/cloudtrail/pkg/cloudtrail/extract.go
> /kind bug
> /kind design
/kind feature
/area plugins
> /area build
This PR adds two new fields to the `cloudtrail` plugin that extract the values of the `requestParameters.policyName` and `requestParameters.roleName` fields from AWS Cloudtrail events. These new fields provide useful information for rules that monitor IAM role and policy change behaviors.
Fixes #
=> feat(cloudtrail): add iam.role and iam.policy fields

plugins/k8saudit/README.md, plugins/k8saudit/go.mod, plugins/k8saudit/go.sum, plugins/k8saudit/pkg/k8saudit/extract.go, plugins/k8saudit/pkg/k8saudit/source.go
Add the ability to extract the location of string values in each log message.
> /kind bug
> /kind design
/kind feature
/area plugins
> /area build
Fixes #
=> update(k8saudit): Add support for field offsets

plugins/container/CMakeLists.txt, plugins/container/go-worker/pkg/container/cri.go, plugins/container/go-worker/pkg/container/docker.go
/kind bug
> /kind design
/area plugins
> /area build
Fixes #943 
=> fix(plugins/container): avoid seg fault

build/registry/go.mod, build/registry/go.sum
See https://github.com/falcosecurity/plugin-sdk-go/commit/6f778b5adc3cc99b62877fbc301e191e01411487
/kind bug
> /kind design
/area build
Fixes #
=> fix(build/registry): re-introduce `RTLD_DEEPBIND` in plugin loader

plugins/anomalydetection/CHANGELOG.md, plugins/cloudtrail/CHANGELOG.md, plugins/collector/CHANGELOG.md, plugins/container/CHANGELOG.md, plugins/dummy/CHANGELOG.md, plugins/dummy_c/CHANGELOG.md, plugins/dummy_rs/CHANGELOG.md, plugins/gcpaudit/CHANGELOG.md, plugins/github/CHANGELOG.md, plugins/json/CHANGELOG.md, plugins/k8saudit-aks/CHANGELOG.md, plugins/k8saudit-eks/CHANGELOG.md, plugins/k8saudit-gke/CHANGELOG.md, plugins/k8saudit-ovh/CHANGELOG.md, plugins/k8saudit/CHANGELOG.md, plugins/k8smeta/CHANGELOG.md, plugins/kafka/CHANGELOG.md, plugins/krsi/CHANGELOG.md, plugins/okta/CHANGELOG.md
> /kind bug
/kind cleanup
> /kind design
/area plugins
> /area build
Fixes #
=> docs(plugins): bulk changelogs update

build/readme/go.mod, build/readme/go.sum, build/readme/readme.go, build/registry/go.mod, build/registry/go.sum
> /kind bug
/kind cleanup
> /kind design
/area build
Fixes #
=> chore(build): bump plugin-go-sdk to v0.8.2

plugins/cloudtrail/pkg/cloudtrail/cloudtrail.go, plugins/dummy_c/dummy.cpp, plugins/dummy_rs/src/libdummy_rs.rs, plugins/gcpaudit/pkg/gcpaudit/gcpaudit.go, plugins/github/pkg/github/github.go, plugins/k8saudit/pkg/k8saudit/k8saudit.go, plugins/kafka/pkg/kafka/kafka.go
/kind bug
> /kind design
/kind feature
/area plugins
> /area build
Fixes #
=> release: bulk release plugin before Falco 0.42 [1/N]

plugins/container/go-worker/worker_test.go
> /kind bug
> /kind design
/area plugins
> /area build
`go-worker` tests have relied on timing. This could make test outcomes non-deterministic. The solution leverages wait groups and channels to make outcomes deterministic.
Fixes #
=> test(container/go-worker): fix flaky tests

plugins/container/CMakeLists.txt, plugins/container/cmake/modules/plugin-sdk-cpp.cmake, plugins/container/src/caps/extract/extract.cpp, plugins/container/src/caps/parse/parse.cpp, plugins/container/src/consts.h, plugins/container/src/macros.h.in, plugins/container/src/plugin.cpp, plugins/container/src/plugin.h
> /kind bug
> /kind design
/kind feature
/area plugins
> /area build
This PR provides support for event schema versions compatible with `4.0.0` and, at the same time, drops support for event schema versions not compatible with it. Specifically, this results in:
- dropping support for some old events and correctly managing possibly-empty parameters
- implementing the plugin symbol `get_required_event_schema_version` to return "4.0.0"
Contextually, this PR bumps the `container` plugin …
=> feat(plugins/container)!: bump required schema version to `4.0.0`

plugins/container/src/macros.h.in
> /kind bug
/kind cleanup
> /kind design
/area plugins
> /area build
We need this to release a release candidate. Primarily for testing purposes.
Fixes #
=> chore(plugins/container): bump to v0.4.0-rc1
